"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _Race:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _RaceEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_Race.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    NoRace: _Race.ValueType  # 0
    Terran: _Race.ValueType  # 1
    Zerg: _Race.ValueType  # 2
    Protoss: _Race.ValueType  # 3
    Random: _Race.ValueType  # 4

class Race(_Race, metaclass=_RaceEnumTypeWrapper): ...

NoRace: Race.ValueType  # 0
Terran: Race.ValueType  # 1
Zerg: Race.ValueType  # 2
Protoss: Race.ValueType  # 3
Random: Race.ValueType  # 4
Global___Race: _TypeAlias = Race  # noqa: Y015

@_typing.final
class AvailableAbility(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ABILITY_ID_FIELD_NUMBER: _builtins.int
    REQUIRES_POINT_FIELD_NUMBER: _builtins.int
    ability_id: _builtins.int
    requires_point: _builtins.bool
    def __init__(
        self,
        *,
        ability_id: _builtins.int | None = ...,
        requires_point: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["ability_id", b"ability_id", "requires_point", b"requires_point"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ability_id", b"ability_id", "requires_point", b"requires_point"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AvailableAbility: _TypeAlias = AvailableAbility  # noqa: Y015

@_typing.final
class ImageData(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BITS_PER_PIXEL_FIELD_NUMBER: _builtins.int
    SIZE_FIELD_NUMBER: _builtins.int
    DATA_FIELD_NUMBER: _builtins.int
    bits_per_pixel: _builtins.int
    """Number of bits per pixel; 8 bits for a byte etc."""
    data: _builtins.bytes
    """Binary data; the size of this buffer in bytes is width * height * bits_per_pixel / 8."""
    @_builtins.property
    def size(self) -> Global___Size2DI:
        """Dimension in pixels."""

    def __init__(
        self,
        *,
        bits_per_pixel: _builtins.int | None = ...,
        size: Global___Size2DI | None = ...,
        data: _builtins.bytes | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["bits_per_pixel", b"bits_per_pixel", "data", b"data", "size", b"size"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bits_per_pixel", b"bits_per_pixel", "data", b"data", "size", b"size"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ImageData: _TypeAlias = ImageData  # noqa: Y015

@_typing.final
class PointI(_message.Message):
    """Point on the screen/minimap (e.g., 0..64).
    Note: bottom left of the screen is 0, 0.
    """

    DESCRIPTOR: _descriptor.Descriptor

    X_FIELD_NUMBER: _builtins.int
    Y_FIELD_NUMBER: _builtins.int
    x: _builtins.int
    y: _builtins.int
    def __init__(
        self,
        *,
        x: _builtins.int | None = ...,
        y: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["x", b"x", "y", b"y"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["x", b"x", "y", b"y"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PointI: _TypeAlias = PointI  # noqa: Y015

@_typing.final
class RectangleI(_message.Message):
    """Screen space rectangular area."""

    DESCRIPTOR: _descriptor.Descriptor

    P0_FIELD_NUMBER: _builtins.int
    P1_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def p0(self) -> Global___PointI: ...
    @_builtins.property
    def p1(self) -> Global___PointI: ...
    def __init__(
        self,
        *,
        p0: Global___PointI | None = ...,
        p1: Global___PointI | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["p0", b"p0", "p1", b"p1"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["p0", b"p0", "p1", b"p1"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RectangleI: _TypeAlias = RectangleI  # noqa: Y015

@_typing.final
class Point2D(_message.Message):
    """Point on the game board, 0..255.
    Note: bottom left of the screen is 0, 0.
    """

    DESCRIPTOR: _descriptor.Descriptor

    X_FIELD_NUMBER: _builtins.int
    Y_FIELD_NUMBER: _builtins.int
    x: _builtins.float
    y: _builtins.float
    def __init__(
        self,
        *,
        x: _builtins.float | None = ...,
        y: _builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["x", b"x", "y", b"y"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["x", b"x", "y", b"y"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Point2D: _TypeAlias = Point2D  # noqa: Y015

@_typing.final
class Point(_message.Message):
    """Point on the game board, 0..255.
    Note: bottom left of the screen is 0, 0.
    """

    DESCRIPTOR: _descriptor.Descriptor

    X_FIELD_NUMBER: _builtins.int
    Y_FIELD_NUMBER: _builtins.int
    Z_FIELD_NUMBER: _builtins.int
    x: _builtins.float
    y: _builtins.float
    z: _builtins.float
    def __init__(
        self,
        *,
        x: _builtins.float | None = ...,
        y: _builtins.float | None = ...,
        z: _builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["x", b"x", "y", b"y", "z", b"z"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["x", b"x", "y", b"y", "z", b"z"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Point: _TypeAlias = Point  # noqa: Y015

@_typing.final
class Size2DI(_message.Message):
    """Screen dimensions."""

    DESCRIPTOR: _descriptor.Descriptor

    X_FIELD_NUMBER: _builtins.int
    Y_FIELD_NUMBER: _builtins.int
    x: _builtins.int
    y: _builtins.int
    def __init__(
        self,
        *,
        x: _builtins.int | None = ...,
        y: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["x", b"x", "y", b"y"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["x", b"x", "y", b"y"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Size2DI: _TypeAlias = Size2DI  # noqa: Y015
