"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from s2clientprotocol import common_pb2 as _common_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _Attribute:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _AttributeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_Attribute.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    Light: _Attribute.ValueType  # 1
    Armored: _Attribute.ValueType  # 2
    Biological: _Attribute.ValueType  # 3
    Mechanical: _Attribute.ValueType  # 4
    Robotic: _Attribute.ValueType  # 5
    Psionic: _Attribute.ValueType  # 6
    Massive: _Attribute.ValueType  # 7
    Structure: _Attribute.ValueType  # 8
    Hover: _Attribute.ValueType  # 9
    Heroic: _Attribute.ValueType  # 10
    Summoned: _Attribute.ValueType  # 11

class Attribute(_Attribute, metaclass=_AttributeEnumTypeWrapper): ...

Light: Attribute.ValueType  # 1
Armored: Attribute.ValueType  # 2
Biological: Attribute.ValueType  # 3
Mechanical: Attribute.ValueType  # 4
Robotic: Attribute.ValueType  # 5
Psionic: Attribute.ValueType  # 6
Massive: Attribute.ValueType  # 7
Structure: Attribute.ValueType  # 8
Hover: Attribute.ValueType  # 9
Heroic: Attribute.ValueType  # 10
Summoned: Attribute.ValueType  # 11
Global___Attribute: _TypeAlias = Attribute  # noqa: Y015

@_typing.final
class AbilityData(_message.Message):
    """May not relevant: queueable (everything is queueable).
    May not be important: AbilSetId - marine stim, marauder stim.
    Stuff omitted: transient.
    Stuff that may be important: cost, range, Alignment, targetfilters.
    """

    DESCRIPTOR: _descriptor.Descriptor

    class _Target:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _TargetEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[AbilityData._Target.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        Point: AbilityData._Target.ValueType  # 2
        """Requires a target position."""
        Unit: AbilityData._Target.ValueType  # 3
        """Requires a unit to target. Given by position using feature layers."""
        PointOrUnit: AbilityData._Target.ValueType  # 4
        """Requires either a target point or target unit."""
        PointOrNone: AbilityData._Target.ValueType  # 5
        """Requires either a target point or no target. (eg. building add-ons)"""

    class Target(_Target, metaclass=_TargetEnumTypeWrapper): ...
    Point: AbilityData.Target.ValueType  # 2
    """Requires a target position."""
    Unit: AbilityData.Target.ValueType  # 3
    """Requires a unit to target. Given by position using feature layers."""
    PointOrUnit: AbilityData.Target.ValueType  # 4
    """Requires either a target point or target unit."""
    PointOrNone: AbilityData.Target.ValueType  # 5
    """Requires either a target point or no target. (eg. building add-ons)"""

    ABILITY_ID_FIELD_NUMBER: _builtins.int
    LINK_NAME_FIELD_NUMBER: _builtins.int
    LINK_INDEX_FIELD_NUMBER: _builtins.int
    BUTTON_NAME_FIELD_NUMBER: _builtins.int
    FRIENDLY_NAME_FIELD_NUMBER: _builtins.int
    HOTKEY_FIELD_NUMBER: _builtins.int
    REMAPS_TO_ABILITY_ID_FIELD_NUMBER: _builtins.int
    AVAILABLE_FIELD_NUMBER: _builtins.int
    TARGET_FIELD_NUMBER: _builtins.int
    ALLOW_MINIMAP_FIELD_NUMBER: _builtins.int
    ALLOW_AUTOCAST_FIELD_NUMBER: _builtins.int
    IS_BUILDING_FIELD_NUMBER: _builtins.int
    FOOTPRINT_RADIUS_FIELD_NUMBER: _builtins.int
    IS_INSTANT_PLACEMENT_FIELD_NUMBER: _builtins.int
    CAST_RANGE_FIELD_NUMBER: _builtins.int
    ability_id: _builtins.int
    """Stable ID."""
    link_name: _builtins.str
    """Catalog name of the ability."""
    link_index: _builtins.int
    """Catalog index of the ability."""
    button_name: _builtins.str
    """Name used for the command card. May not always be set."""
    friendly_name: _builtins.str
    """A human friendly name when the button name or link name isn't descriptive."""
    hotkey: _builtins.str
    """Hotkey. May not always be set."""
    remaps_to_ability_id: _builtins.int
    """This ability id may be represented by the given more generic id."""
    available: _builtins.bool
    """If true, the ability may be used by this set of mods/map."""
    target: Global___AbilityData.Target.ValueType
    """Determines if a point is optional or required."""
    allow_minimap: _builtins.bool
    """Can be cast in the minimap."""
    allow_autocast: _builtins.bool
    """Autocast can be set."""
    is_building: _builtins.bool
    """Requires placement to construct a building."""
    footprint_radius: _builtins.float
    """Estimation of the footprint size. Need a better footprint."""
    is_instant_placement: _builtins.bool
    """Placement next to an existing structure, e.g., an add-on like a Tech Lab."""
    cast_range: _builtins.float
    """Range unit can cast ability without needing to approach target."""
    def __init__(
        self,
        *,
        ability_id: _builtins.int | None = ...,
        link_name: _builtins.str | None = ...,
        link_index: _builtins.int | None = ...,
        button_name: _builtins.str | None = ...,
        friendly_name: _builtins.str | None = ...,
        hotkey: _builtins.str | None = ...,
        remaps_to_ability_id: _builtins.int | None = ...,
        available: _builtins.bool | None = ...,
        target: Global___AbilityData.Target.ValueType | None = ...,
        allow_minimap: _builtins.bool | None = ...,
        allow_autocast: _builtins.bool | None = ...,
        is_building: _builtins.bool | None = ...,
        footprint_radius: _builtins.float | None = ...,
        is_instant_placement: _builtins.bool | None = ...,
        cast_range: _builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["ability_id", b"ability_id", "allow_autocast", b"allow_autocast", "allow_minimap", b"allow_minimap", "available", b"available", "button_name", b"button_name", "cast_range", b"cast_range", "footprint_radius", b"footprint_radius", "friendly_name", b"friendly_name", "hotkey", b"hotkey", "is_building", b"is_building", "is_instant_placement", b"is_instant_placement", "link_index", b"link_index", "link_name", b"link_name", "remaps_to_ability_id", b"remaps_to_ability_id", "target", b"target"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ability_id", b"ability_id", "allow_autocast", b"allow_autocast", "allow_minimap", b"allow_minimap", "available", b"available", "button_name", b"button_name", "cast_range", b"cast_range", "footprint_radius", b"footprint_radius", "friendly_name", b"friendly_name", "hotkey", b"hotkey", "is_building", b"is_building", "is_instant_placement", b"is_instant_placement", "link_index", b"link_index", "link_name", b"link_name", "remaps_to_ability_id", b"remaps_to_ability_id", "target", b"target"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AbilityData: _TypeAlias = AbilityData  # noqa: Y015

@_typing.final
class DamageBonus(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ATTRIBUTE_FIELD_NUMBER: _builtins.int
    BONUS_FIELD_NUMBER: _builtins.int
    attribute: Global___Attribute.ValueType
    bonus: _builtins.float
    def __init__(
        self,
        *,
        attribute: Global___Attribute.ValueType | None = ...,
        bonus: _builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["attribute", b"attribute", "bonus", b"bonus"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["attribute", b"attribute", "bonus", b"bonus"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DamageBonus: _TypeAlias = DamageBonus  # noqa: Y015

@_typing.final
class Weapon(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _TargetType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _TargetTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Weapon._TargetType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        Ground: Weapon._TargetType.ValueType  # 1
        Air: Weapon._TargetType.ValueType  # 2
        Any: Weapon._TargetType.ValueType  # 3

    class TargetType(_TargetType, metaclass=_TargetTypeEnumTypeWrapper): ...
    Ground: Weapon.TargetType.ValueType  # 1
    Air: Weapon.TargetType.ValueType  # 2
    Any: Weapon.TargetType.ValueType  # 3

    TYPE_FIELD_NUMBER: _builtins.int
    DAMAGE_FIELD_NUMBER: _builtins.int
    DAMAGE_BONUS_FIELD_NUMBER: _builtins.int
    ATTACKS_FIELD_NUMBER: _builtins.int
    RANGE_FIELD_NUMBER: _builtins.int
    SPEED_FIELD_NUMBER: _builtins.int
    type: Global___Weapon.TargetType.ValueType
    damage: _builtins.float
    attacks: _builtins.int
    """Number of hits per attack. (eg. Colossus has 2 beams)"""
    range: _builtins.float
    speed: _builtins.float
    """Time between attacks."""
    @_builtins.property
    def damage_bonus(self) -> _containers.RepeatedCompositeFieldContainer[Global___DamageBonus]: ...
    def __init__(
        self,
        *,
        type: Global___Weapon.TargetType.ValueType | None = ...,
        damage: _builtins.float | None = ...,
        damage_bonus: _abc.Iterable[Global___DamageBonus] | None = ...,
        attacks: _builtins.int | None = ...,
        range: _builtins.float | None = ...,
        speed: _builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["attacks", b"attacks", "damage", b"damage", "range", b"range", "speed", b"speed", "type", b"type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["attacks", b"attacks", "damage", b"damage", "damage_bonus", b"damage_bonus", "range", b"range", "speed", b"speed", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Weapon: _TypeAlias = Weapon  # noqa: Y015

@_typing.final
class UnitTypeData(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    UNIT_ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    AVAILABLE_FIELD_NUMBER: _builtins.int
    CARGO_SIZE_FIELD_NUMBER: _builtins.int
    MINERAL_COST_FIELD_NUMBER: _builtins.int
    VESPENE_COST_FIELD_NUMBER: _builtins.int
    FOOD_REQUIRED_FIELD_NUMBER: _builtins.int
    FOOD_PROVIDED_FIELD_NUMBER: _builtins.int
    ABILITY_ID_FIELD_NUMBER: _builtins.int
    RACE_FIELD_NUMBER: _builtins.int
    BUILD_TIME_FIELD_NUMBER: _builtins.int
    HAS_VESPENE_FIELD_NUMBER: _builtins.int
    HAS_MINERALS_FIELD_NUMBER: _builtins.int
    SIGHT_RANGE_FIELD_NUMBER: _builtins.int
    TECH_ALIAS_FIELD_NUMBER: _builtins.int
    UNIT_ALIAS_FIELD_NUMBER: _builtins.int
    TECH_REQUIREMENT_FIELD_NUMBER: _builtins.int
    REQUIRE_ATTACHED_FIELD_NUMBER: _builtins.int
    ATTRIBUTES_FIELD_NUMBER: _builtins.int
    MOVEMENT_SPEED_FIELD_NUMBER: _builtins.int
    ARMOR_FIELD_NUMBER: _builtins.int
    WEAPONS_FIELD_NUMBER: _builtins.int
    unit_id: _builtins.int
    """Stable ID."""
    name: _builtins.str
    """Catalog name of the unit."""
    available: _builtins.bool
    """If true, the ability may be used by this set of mods/map."""
    cargo_size: _builtins.int
    """Number of cargo slots it occupies in transports."""
    mineral_cost: _builtins.int
    vespene_cost: _builtins.int
    food_required: _builtins.float
    food_provided: _builtins.float
    ability_id: _builtins.int
    """The ability that builds this unit."""
    race: _common_pb2.Race.ValueType
    build_time: _builtins.float
    has_vespene: _builtins.bool
    has_minerals: _builtins.bool
    sight_range: _builtins.float
    """Range unit reveals vision."""
    unit_alias: _builtins.int
    """The morphed variant of this unit."""
    tech_requirement: _builtins.int
    """Structure required to build this unit. (Or any with the same tech_alias)"""
    require_attached: _builtins.bool
    """Whether tech_requirement is an add-on."""
    movement_speed: _builtins.float
    armor: _builtins.float
    @_builtins.property
    def tech_alias(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """Other units that satisfy the same tech requirement."""

    @_builtins.property
    def attributes(self) -> _containers.RepeatedScalarFieldContainer[Global___Attribute.ValueType]:
        """Values include changes from upgrades"""

    @_builtins.property
    def weapons(self) -> _containers.RepeatedCompositeFieldContainer[Global___Weapon]: ...
    def __init__(
        self,
        *,
        unit_id: _builtins.int | None = ...,
        name: _builtins.str | None = ...,
        available: _builtins.bool | None = ...,
        cargo_size: _builtins.int | None = ...,
        mineral_cost: _builtins.int | None = ...,
        vespene_cost: _builtins.int | None = ...,
        food_required: _builtins.float | None = ...,
        food_provided: _builtins.float | None = ...,
        ability_id: _builtins.int | None = ...,
        race: _common_pb2.Race.ValueType | None = ...,
        build_time: _builtins.float | None = ...,
        has_vespene: _builtins.bool | None = ...,
        has_minerals: _builtins.bool | None = ...,
        sight_range: _builtins.float | None = ...,
        tech_alias: _abc.Iterable[_builtins.int] | None = ...,
        unit_alias: _builtins.int | None = ...,
        tech_requirement: _builtins.int | None = ...,
        require_attached: _builtins.bool | None = ...,
        attributes: _abc.Iterable[Global___Attribute.ValueType] | None = ...,
        movement_speed: _builtins.float | None = ...,
        armor: _builtins.float | None = ...,
        weapons: _abc.Iterable[Global___Weapon] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["ability_id", b"ability_id", "armor", b"armor", "available", b"available", "build_time", b"build_time", "cargo_size", b"cargo_size", "food_provided", b"food_provided", "food_required", b"food_required", "has_minerals", b"has_minerals", "has_vespene", b"has_vespene", "mineral_cost", b"mineral_cost", "movement_speed", b"movement_speed", "name", b"name", "race", b"race", "require_attached", b"require_attached", "sight_range", b"sight_range", "tech_requirement", b"tech_requirement", "unit_alias", b"unit_alias", "unit_id", b"unit_id", "vespene_cost", b"vespene_cost"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ability_id", b"ability_id", "armor", b"armor", "attributes", b"attributes", "available", b"available", "build_time", b"build_time", "cargo_size", b"cargo_size", "food_provided", b"food_provided", "food_required", b"food_required", "has_minerals", b"has_minerals", "has_vespene", b"has_vespene", "mineral_cost", b"mineral_cost", "movement_speed", b"movement_speed", "name", b"name", "race", b"race", "require_attached", b"require_attached", "sight_range", b"sight_range", "tech_alias", b"tech_alias", "tech_requirement", b"tech_requirement", "unit_alias", b"unit_alias", "unit_id", b"unit_id", "vespene_cost", b"vespene_cost", "weapons", b"weapons"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UnitTypeData: _TypeAlias = UnitTypeData  # noqa: Y015

@_typing.final
class UpgradeData(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    UPGRADE_ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    MINERAL_COST_FIELD_NUMBER: _builtins.int
    VESPENE_COST_FIELD_NUMBER: _builtins.int
    RESEARCH_TIME_FIELD_NUMBER: _builtins.int
    ABILITY_ID_FIELD_NUMBER: _builtins.int
    upgrade_id: _builtins.int
    """Stable ID."""
    name: _builtins.str
    mineral_cost: _builtins.int
    vespene_cost: _builtins.int
    research_time: _builtins.float
    ability_id: _builtins.int
    def __init__(
        self,
        *,
        upgrade_id: _builtins.int | None = ...,
        name: _builtins.str | None = ...,
        mineral_cost: _builtins.int | None = ...,
        vespene_cost: _builtins.int | None = ...,
        research_time: _builtins.float | None = ...,
        ability_id: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["ability_id", b"ability_id", "mineral_cost", b"mineral_cost", "name", b"name", "research_time", b"research_time", "upgrade_id", b"upgrade_id", "vespene_cost", b"vespene_cost"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ability_id", b"ability_id", "mineral_cost", b"mineral_cost", "name", b"name", "research_time", b"research_time", "upgrade_id", b"upgrade_id", "vespene_cost", b"vespene_cost"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UpgradeData: _TypeAlias = UpgradeData  # noqa: Y015

@_typing.final
class BuffData(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BUFF_ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    buff_id: _builtins.int
    """Stable ID."""
    name: _builtins.str
    def __init__(
        self,
        *,
        buff_id: _builtins.int | None = ...,
        name: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["buff_id", b"buff_id", "name", b"name"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["buff_id", b"buff_id", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___BuffData: _TypeAlias = BuffData  # noqa: Y015

@_typing.final
class EffectData(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EFFECT_ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    FRIENDLY_NAME_FIELD_NUMBER: _builtins.int
    RADIUS_FIELD_NUMBER: _builtins.int
    effect_id: _builtins.int
    """Stable ID."""
    name: _builtins.str
    friendly_name: _builtins.str
    radius: _builtins.float
    def __init__(
        self,
        *,
        effect_id: _builtins.int | None = ...,
        name: _builtins.str | None = ...,
        friendly_name: _builtins.str | None = ...,
        radius: _builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["effect_id", b"effect_id", "friendly_name", b"friendly_name", "name", b"name", "radius", b"radius"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["effect_id", b"effect_id", "friendly_name", b"friendly_name", "name", b"name", "radius", b"radius"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EffectData: _TypeAlias = EffectData  # noqa: Y015
