"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from s2clientprotocol import common_pb2 as _common_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _DebugGameState:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _DebugGameStateEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_DebugGameState.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    show_map: _DebugGameState.ValueType  # 1
    control_enemy: _DebugGameState.ValueType  # 2
    food: _DebugGameState.ValueType  # 3
    free: _DebugGameState.ValueType  # 4
    all_resources: _DebugGameState.ValueType  # 5
    god: _DebugGameState.ValueType  # 6
    minerals: _DebugGameState.ValueType  # 7
    gas: _DebugGameState.ValueType  # 8
    cooldown: _DebugGameState.ValueType  # 9
    tech_tree: _DebugGameState.ValueType  # 10
    upgrade: _DebugGameState.ValueType  # 11
    fast_build: _DebugGameState.ValueType  # 12

class DebugGameState(_DebugGameState, metaclass=_DebugGameStateEnumTypeWrapper): ...

show_map: DebugGameState.ValueType  # 1
control_enemy: DebugGameState.ValueType  # 2
food: DebugGameState.ValueType  # 3
free: DebugGameState.ValueType  # 4
all_resources: DebugGameState.ValueType  # 5
god: DebugGameState.ValueType  # 6
minerals: DebugGameState.ValueType  # 7
gas: DebugGameState.ValueType  # 8
cooldown: DebugGameState.ValueType  # 9
tech_tree: DebugGameState.ValueType  # 10
upgrade: DebugGameState.ValueType  # 11
fast_build: DebugGameState.ValueType  # 12
Global___DebugGameState: _TypeAlias = DebugGameState  # noqa: Y015

@_typing.final
class DebugCommand(_message.Message):
    """Issue various useful commands to the game engine."""

    DESCRIPTOR: _descriptor.Descriptor

    DRAW_FIELD_NUMBER: _builtins.int
    GAME_STATE_FIELD_NUMBER: _builtins.int
    CREATE_UNIT_FIELD_NUMBER: _builtins.int
    KILL_UNIT_FIELD_NUMBER: _builtins.int
    TEST_PROCESS_FIELD_NUMBER: _builtins.int
    SCORE_FIELD_NUMBER: _builtins.int
    END_GAME_FIELD_NUMBER: _builtins.int
    UNIT_VALUE_FIELD_NUMBER: _builtins.int
    game_state: Global___DebugGameState.ValueType
    @_builtins.property
    def draw(self) -> Global___DebugDraw: ...
    @_builtins.property
    def create_unit(self) -> Global___DebugCreateUnit: ...
    @_builtins.property
    def kill_unit(self) -> Global___DebugKillUnit: ...
    @_builtins.property
    def test_process(self) -> Global___DebugTestProcess: ...
    @_builtins.property
    def score(self) -> Global___DebugSetScore:
        """Useful only for single-player "curriculum" maps."""

    @_builtins.property
    def end_game(self) -> Global___DebugEndGame: ...
    @_builtins.property
    def unit_value(self) -> Global___DebugSetUnitValue: ...
    def __init__(
        self,
        *,
        draw: Global___DebugDraw | None = ...,
        game_state: Global___DebugGameState.ValueType | None = ...,
        create_unit: Global___DebugCreateUnit | None = ...,
        kill_unit: Global___DebugKillUnit | None = ...,
        test_process: Global___DebugTestProcess | None = ...,
        score: Global___DebugSetScore | None = ...,
        end_game: Global___DebugEndGame | None = ...,
        unit_value: Global___DebugSetUnitValue | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["command", b"command", "create_unit", b"create_unit", "draw", b"draw", "end_game", b"end_game", "game_state", b"game_state", "kill_unit", b"kill_unit", "score", b"score", "test_process", b"test_process", "unit_value", b"unit_value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["command", b"command", "create_unit", b"create_unit", "draw", b"draw", "end_game", b"end_game", "game_state", b"game_state", "kill_unit", b"kill_unit", "score", b"score", "test_process", b"test_process", "unit_value", b"unit_value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_command: _TypeAlias = _typing.Literal["draw", "game_state", "create_unit", "kill_unit", "test_process", "score", "end_game", "unit_value"]  # noqa: Y015
    _WhichOneofArgType_command: _TypeAlias = _typing.Literal["command", b"command"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_command) -> _WhichOneofReturnType_command | None: ...

Global___DebugCommand: _TypeAlias = DebugCommand  # noqa: Y015

@_typing.final
class DebugDraw(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TEXT_FIELD_NUMBER: _builtins.int
    LINES_FIELD_NUMBER: _builtins.int
    BOXES_FIELD_NUMBER: _builtins.int
    SPHERES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def text(self) -> _containers.RepeatedCompositeFieldContainer[Global___DebugText]: ...
    @_builtins.property
    def lines(self) -> _containers.RepeatedCompositeFieldContainer[Global___DebugLine]: ...
    @_builtins.property
    def boxes(self) -> _containers.RepeatedCompositeFieldContainer[Global___DebugBox]: ...
    @_builtins.property
    def spheres(self) -> _containers.RepeatedCompositeFieldContainer[Global___DebugSphere]: ...
    def __init__(
        self,
        *,
        text: _abc.Iterable[Global___DebugText] | None = ...,
        lines: _abc.Iterable[Global___DebugLine] | None = ...,
        boxes: _abc.Iterable[Global___DebugBox] | None = ...,
        spheres: _abc.Iterable[Global___DebugSphere] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["boxes", b"boxes", "lines", b"lines", "spheres", b"spheres", "text", b"text"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DebugDraw: _TypeAlias = DebugDraw  # noqa: Y015

@_typing.final
class Line(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    P0_FIELD_NUMBER: _builtins.int
    P1_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def p0(self) -> _common_pb2.Point: ...
    @_builtins.property
    def p1(self) -> _common_pb2.Point: ...
    def __init__(
        self,
        *,
        p0: _common_pb2.Point | None = ...,
        p1: _common_pb2.Point | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["p0", b"p0", "p1", b"p1"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["p0", b"p0", "p1", b"p1"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Line: _TypeAlias = Line  # noqa: Y015

@_typing.final
class Color(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    R_FIELD_NUMBER: _builtins.int
    G_FIELD_NUMBER: _builtins.int
    B_FIELD_NUMBER: _builtins.int
    r: _builtins.int
    g: _builtins.int
    b: _builtins.int
    def __init__(
        self,
        *,
        r: _builtins.int | None = ...,
        g: _builtins.int | None = ...,
        b: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["b", b"b", "g", b"g", "r", b"r"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["b", b"b", "g", b"g", "r", b"r"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Color: _TypeAlias = Color  # noqa: Y015

@_typing.final
class DebugText(_message.Message):
    """Display debug text on screen."""

    DESCRIPTOR: _descriptor.Descriptor

    COLOR_FIELD_NUMBER: _builtins.int
    TEXT_FIELD_NUMBER: _builtins.int
    VIRTUAL_POS_FIELD_NUMBER: _builtins.int
    WORLD_POS_FIELD_NUMBER: _builtins.int
    SIZE_FIELD_NUMBER: _builtins.int
    text: _builtins.str
    """Text to display."""
    size: _builtins.int
    """Pixel height of the text. Defaults to 8px."""
    @_builtins.property
    def color(self) -> Global___Color: ...
    @_builtins.property
    def virtual_pos(self) -> _common_pb2.Point:
        """Virtualized position in 2D (the screen is 0..1, 0..1 for any resolution)."""

    @_builtins.property
    def world_pos(self) -> _common_pb2.Point:
        """Position in the world."""

    def __init__(
        self,
        *,
        color: Global___Color | None = ...,
        text: _builtins.str | None = ...,
        virtual_pos: _common_pb2.Point | None = ...,
        world_pos: _common_pb2.Point | None = ...,
        size: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["color", b"color", "size", b"size", "text", b"text", "virtual_pos", b"virtual_pos", "world_pos", b"world_pos"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["color", b"color", "size", b"size", "text", b"text", "virtual_pos", b"virtual_pos", "world_pos", b"world_pos"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DebugText: _TypeAlias = DebugText  # noqa: Y015

@_typing.final
class DebugLine(_message.Message):
    """Display debug lines on screen."""

    DESCRIPTOR: _descriptor.Descriptor

    COLOR_FIELD_NUMBER: _builtins.int
    LINE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def color(self) -> Global___Color: ...
    @_builtins.property
    def line(self) -> Global___Line:
        """World space line."""

    def __init__(
        self,
        *,
        color: Global___Color | None = ...,
        line: Global___Line | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["color", b"color", "line", b"line"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["color", b"color", "line", b"line"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DebugLine: _TypeAlias = DebugLine  # noqa: Y015

@_typing.final
class DebugBox(_message.Message):
    """Display debug boxes on screen."""

    DESCRIPTOR: _descriptor.Descriptor

    COLOR_FIELD_NUMBER: _builtins.int
    MIN_FIELD_NUMBER: _builtins.int
    MAX_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def color(self) -> Global___Color: ...
    @_builtins.property
    def min(self) -> _common_pb2.Point: ...
    @_builtins.property
    def max(self) -> _common_pb2.Point: ...
    def __init__(
        self,
        *,
        color: Global___Color | None = ...,
        min: _common_pb2.Point | None = ...,
        max: _common_pb2.Point | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["color", b"color", "max", b"max", "min", b"min"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["color", b"color", "max", b"max", "min", b"min"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DebugBox: _TypeAlias = DebugBox  # noqa: Y015

@_typing.final
class DebugSphere(_message.Message):
    """Display debug spheres on screen."""

    DESCRIPTOR: _descriptor.Descriptor

    COLOR_FIELD_NUMBER: _builtins.int
    P_FIELD_NUMBER: _builtins.int
    R_FIELD_NUMBER: _builtins.int
    r: _builtins.float
    @_builtins.property
    def color(self) -> Global___Color: ...
    @_builtins.property
    def p(self) -> _common_pb2.Point: ...
    def __init__(
        self,
        *,
        color: Global___Color | None = ...,
        p: _common_pb2.Point | None = ...,
        r: _builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["color", b"color", "p", b"p", "r", b"r"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["color", b"color", "p", b"p", "r", b"r"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DebugSphere: _TypeAlias = DebugSphere  # noqa: Y015

@_typing.final
class DebugCreateUnit(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    UNIT_TYPE_FIELD_NUMBER: _builtins.int
    OWNER_FIELD_NUMBER: _builtins.int
    POS_FIELD_NUMBER: _builtins.int
    QUANTITY_FIELD_NUMBER: _builtins.int
    unit_type: _builtins.int
    owner: _builtins.int
    quantity: _builtins.int
    @_builtins.property
    def pos(self) -> _common_pb2.Point2D: ...
    def __init__(
        self,
        *,
        unit_type: _builtins.int | None = ...,
        owner: _builtins.int | None = ...,
        pos: _common_pb2.Point2D | None = ...,
        quantity: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["owner", b"owner", "pos", b"pos", "quantity", b"quantity", "unit_type", b"unit_type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["owner", b"owner", "pos", b"pos", "quantity", b"quantity", "unit_type", b"unit_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DebugCreateUnit: _TypeAlias = DebugCreateUnit  # noqa: Y015

@_typing.final
class DebugKillUnit(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TAG_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def tag(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        tag: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["tag", b"tag"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DebugKillUnit: _TypeAlias = DebugKillUnit  # noqa: Y015

@_typing.final
class DebugTestProcess(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Test:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _TestEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[DebugTestProcess._Test.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        hang: DebugTestProcess._Test.ValueType  # 1
        crash: DebugTestProcess._Test.ValueType  # 2
        exit: DebugTestProcess._Test.ValueType  # 3

    class Test(_Test, metaclass=_TestEnumTypeWrapper): ...
    hang: DebugTestProcess.Test.ValueType  # 1
    crash: DebugTestProcess.Test.ValueType  # 2
    exit: DebugTestProcess.Test.ValueType  # 3

    TEST_FIELD_NUMBER: _builtins.int
    DELAY_MS_FIELD_NUMBER: _builtins.int
    test: Global___DebugTestProcess.Test.ValueType
    delay_ms: _builtins.int
    def __init__(
        self,
        *,
        test: Global___DebugTestProcess.Test.ValueType | None = ...,
        delay_ms: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["delay_ms", b"delay_ms", "test", b"test"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["delay_ms", b"delay_ms", "test", b"test"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DebugTestProcess: _TypeAlias = DebugTestProcess  # noqa: Y015

@_typing.final
class DebugSetScore(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SCORE_FIELD_NUMBER: _builtins.int
    score: _builtins.float
    def __init__(
        self,
        *,
        score: _builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["score", b"score"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["score", b"score"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DebugSetScore: _TypeAlias = DebugSetScore  # noqa: Y015

@_typing.final
class DebugEndGame(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _EndResult:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _EndResultEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[DebugEndGame._EndResult.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        Surrender: DebugEndGame._EndResult.ValueType  # 1
        """Default if nothing is set. The current player admits defeat."""
        DeclareVictory: DebugEndGame._EndResult.ValueType  # 2

    class EndResult(_EndResult, metaclass=_EndResultEnumTypeWrapper): ...
    Surrender: DebugEndGame.EndResult.ValueType  # 1
    """Default if nothing is set. The current player admits defeat."""
    DeclareVictory: DebugEndGame.EndResult.ValueType  # 2

    END_RESULT_FIELD_NUMBER: _builtins.int
    end_result: Global___DebugEndGame.EndResult.ValueType
    def __init__(
        self,
        *,
        end_result: Global___DebugEndGame.EndResult.ValueType | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["end_result", b"end_result"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["end_result", b"end_result"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DebugEndGame: _TypeAlias = DebugEndGame  # noqa: Y015

@_typing.final
class DebugSetUnitValue(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _UnitValue:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _UnitValueEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[DebugSetUnitValue._UnitValue.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        Energy: DebugSetUnitValue._UnitValue.ValueType  # 1
        Life: DebugSetUnitValue._UnitValue.ValueType  # 2
        Shields: DebugSetUnitValue._UnitValue.ValueType  # 3

    class UnitValue(_UnitValue, metaclass=_UnitValueEnumTypeWrapper): ...
    Energy: DebugSetUnitValue.UnitValue.ValueType  # 1
    Life: DebugSetUnitValue.UnitValue.ValueType  # 2
    Shields: DebugSetUnitValue.UnitValue.ValueType  # 3

    UNIT_VALUE_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    UNIT_TAG_FIELD_NUMBER: _builtins.int
    unit_value: Global___DebugSetUnitValue.UnitValue.ValueType
    value: _builtins.float
    unit_tag: _builtins.int
    def __init__(
        self,
        *,
        unit_value: Global___DebugSetUnitValue.UnitValue.ValueType | None = ...,
        value: _builtins.float | None = ...,
        unit_tag: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["unit_tag", b"unit_tag", "unit_value", b"unit_value", "value", b"value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["unit_tag", b"unit_tag", "unit_value", b"unit_value", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DebugSetUnitValue: _TypeAlias = DebugSetUnitValue  # noqa: Y015
