"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from s2clientprotocol import common_pb2 as _common_pb2
from s2clientprotocol import error_pb2 as _error_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class RequestQuery(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PATHING_FIELD_NUMBER: _builtins.int
    ABILITIES_FIELD_NUMBER: _builtins.int
    PLACEMENTS_FIELD_NUMBER: _builtins.int
    IGNORE_RESOURCE_REQUIREMENTS_FIELD_NUMBER: _builtins.int
    ignore_resource_requirements: _builtins.bool
    """Ignores requirements like food, minerals and so on."""
    @_builtins.property
    def pathing(self) -> _containers.RepeatedCompositeFieldContainer[Global___RequestQueryPathing]: ...
    @_builtins.property
    def abilities(self) -> _containers.RepeatedCompositeFieldContainer[Global___RequestQueryAvailableAbilities]: ...
    @_builtins.property
    def placements(self) -> _containers.RepeatedCompositeFieldContainer[Global___RequestQueryBuildingPlacement]: ...
    def __init__(
        self,
        *,
        pathing: _abc.Iterable[Global___RequestQueryPathing] | None = ...,
        abilities: _abc.Iterable[Global___RequestQueryAvailableAbilities] | None = ...,
        placements: _abc.Iterable[Global___RequestQueryBuildingPlacement] | None = ...,
        ignore_resource_requirements: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["ignore_resource_requirements", b"ignore_resource_requirements"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["abilities", b"abilities", "ignore_resource_requirements", b"ignore_resource_requirements", "pathing", b"pathing", "placements", b"placements"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RequestQuery: _TypeAlias = RequestQuery  # noqa: Y015

@_typing.final
class ResponseQuery(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PATHING_FIELD_NUMBER: _builtins.int
    ABILITIES_FIELD_NUMBER: _builtins.int
    PLACEMENTS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def pathing(self) -> _containers.RepeatedCompositeFieldContainer[Global___ResponseQueryPathing]: ...
    @_builtins.property
    def abilities(self) -> _containers.RepeatedCompositeFieldContainer[Global___ResponseQueryAvailableAbilities]: ...
    @_builtins.property
    def placements(self) -> _containers.RepeatedCompositeFieldContainer[Global___ResponseQueryBuildingPlacement]: ...
    def __init__(
        self,
        *,
        pathing: _abc.Iterable[Global___ResponseQueryPathing] | None = ...,
        abilities: _abc.Iterable[Global___ResponseQueryAvailableAbilities] | None = ...,
        placements: _abc.Iterable[Global___ResponseQueryBuildingPlacement] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["abilities", b"abilities", "pathing", b"pathing", "placements", b"placements"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ResponseQuery: _TypeAlias = ResponseQuery  # noqa: Y015

@_typing.final
class RequestQueryPathing(_message.Message):
    """--------------------------------------------------------------------------------------------------"""

    DESCRIPTOR: _descriptor.Descriptor

    START_POS_FIELD_NUMBER: _builtins.int
    UNIT_TAG_FIELD_NUMBER: _builtins.int
    END_POS_FIELD_NUMBER: _builtins.int
    unit_tag: _builtins.int
    @_builtins.property
    def start_pos(self) -> _common_pb2.Point2D: ...
    @_builtins.property
    def end_pos(self) -> _common_pb2.Point2D: ...
    def __init__(
        self,
        *,
        start_pos: _common_pb2.Point2D | None = ...,
        unit_tag: _builtins.int | None = ...,
        end_pos: _common_pb2.Point2D | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["end_pos", b"end_pos", "start", b"start", "start_pos", b"start_pos", "unit_tag", b"unit_tag"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["end_pos", b"end_pos", "start", b"start", "start_pos", b"start_pos", "unit_tag", b"unit_tag"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_start: _TypeAlias = _typing.Literal["start_pos", "unit_tag"]  # noqa: Y015
    _WhichOneofArgType_start: _TypeAlias = _typing.Literal["start", b"start"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_start) -> _WhichOneofReturnType_start | None: ...

Global___RequestQueryPathing: _TypeAlias = RequestQueryPathing  # noqa: Y015

@_typing.final
class ResponseQueryPathing(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DISTANCE_FIELD_NUMBER: _builtins.int
    distance: _builtins.float
    """0 if no path exists"""
    def __init__(
        self,
        *,
        distance: _builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["distance", b"distance"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["distance", b"distance"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ResponseQueryPathing: _TypeAlias = ResponseQueryPathing  # noqa: Y015

@_typing.final
class RequestQueryAvailableAbilities(_message.Message):
    """--------------------------------------------------------------------------------------------------"""

    DESCRIPTOR: _descriptor.Descriptor

    UNIT_TAG_FIELD_NUMBER: _builtins.int
    unit_tag: _builtins.int
    def __init__(
        self,
        *,
        unit_tag: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["unit_tag", b"unit_tag"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["unit_tag", b"unit_tag"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RequestQueryAvailableAbilities: _TypeAlias = RequestQueryAvailableAbilities  # noqa: Y015

@_typing.final
class ResponseQueryAvailableAbilities(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ABILITIES_FIELD_NUMBER: _builtins.int
    UNIT_TAG_FIELD_NUMBER: _builtins.int
    UNIT_TYPE_ID_FIELD_NUMBER: _builtins.int
    unit_tag: _builtins.int
    unit_type_id: _builtins.int
    @_builtins.property
    def abilities(self) -> _containers.RepeatedCompositeFieldContainer[_common_pb2.AvailableAbility]: ...
    def __init__(
        self,
        *,
        abilities: _abc.Iterable[_common_pb2.AvailableAbility] | None = ...,
        unit_tag: _builtins.int | None = ...,
        unit_type_id: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["unit_tag", b"unit_tag", "unit_type_id", b"unit_type_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["abilities", b"abilities", "unit_tag", b"unit_tag", "unit_type_id", b"unit_type_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ResponseQueryAvailableAbilities: _TypeAlias = ResponseQueryAvailableAbilities  # noqa: Y015

@_typing.final
class RequestQueryBuildingPlacement(_message.Message):
    """--------------------------------------------------------------------------------------------------"""

    DESCRIPTOR: _descriptor.Descriptor

    ABILITY_ID_FIELD_NUMBER: _builtins.int
    TARGET_POS_FIELD_NUMBER: _builtins.int
    PLACING_UNIT_TAG_FIELD_NUMBER: _builtins.int
    ability_id: _builtins.int
    placing_unit_tag: _builtins.int
    """Not required"""
    @_builtins.property
    def target_pos(self) -> _common_pb2.Point2D: ...
    def __init__(
        self,
        *,
        ability_id: _builtins.int | None = ...,
        target_pos: _common_pb2.Point2D | None = ...,
        placing_unit_tag: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["ability_id", b"ability_id", "placing_unit_tag", b"placing_unit_tag", "target_pos", b"target_pos"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ability_id", b"ability_id", "placing_unit_tag", b"placing_unit_tag", "target_pos", b"target_pos"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RequestQueryBuildingPlacement: _TypeAlias = RequestQueryBuildingPlacement  # noqa: Y015

@_typing.final
class ResponseQueryBuildingPlacement(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RESULT_FIELD_NUMBER: _builtins.int
    result: _error_pb2.ActionResult.ValueType
    def __init__(
        self,
        *,
        result: _error_pb2.ActionResult.ValueType | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["result", b"result"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["result", b"result"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ResponseQueryBuildingPlacement: _TypeAlias = ResponseQueryBuildingPlacement  # noqa: Y015
