"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from s2clientprotocol import common_pb2 as _common_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _DisplayType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _DisplayTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_DisplayType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    Visible: _DisplayType.ValueType  # 1
    """Fully visible"""
    Snapshot: _DisplayType.ValueType  # 2
    """Dimmed version of unit left behind after entering fog of war"""
    Hidden: _DisplayType.ValueType  # 3
    """Fully hidden"""
    Placeholder: _DisplayType.ValueType  # 4
    """Building that hasn't started construction."""

class DisplayType(_DisplayType, metaclass=_DisplayTypeEnumTypeWrapper): ...

Visible: DisplayType.ValueType  # 1
"""Fully visible"""
Snapshot: DisplayType.ValueType  # 2
"""Dimmed version of unit left behind after entering fog of war"""
Hidden: DisplayType.ValueType  # 3
"""Fully hidden"""
Placeholder: DisplayType.ValueType  # 4
"""Building that hasn't started construction."""
Global___DisplayType: _TypeAlias = DisplayType  # noqa: Y015

class _Alliance:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _AllianceEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_Alliance.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    Self: _Alliance.ValueType  # 1
    Ally: _Alliance.ValueType  # 2
    Neutral: _Alliance.ValueType  # 3
    Enemy: _Alliance.ValueType  # 4

class Alliance(_Alliance, metaclass=_AllianceEnumTypeWrapper): ...

Self: Alliance.ValueType  # 1
Ally: Alliance.ValueType  # 2
Neutral: Alliance.ValueType  # 3
Enemy: Alliance.ValueType  # 4
Global___Alliance: _TypeAlias = Alliance  # noqa: Y015

class _CloakState:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _CloakStateEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_CloakState.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    CloakedUnknown: _CloakState.ValueType  # 0
    """Under the fog, so unknown whether it's cloaked or not."""
    Cloaked: _CloakState.ValueType  # 1
    CloakedDetected: _CloakState.ValueType  # 2
    NotCloaked: _CloakState.ValueType  # 3
    CloakedAllied: _CloakState.ValueType  # 4

class CloakState(_CloakState, metaclass=_CloakStateEnumTypeWrapper): ...

CloakedUnknown: CloakState.ValueType  # 0
"""Under the fog, so unknown whether it's cloaked or not."""
Cloaked: CloakState.ValueType  # 1
CloakedDetected: CloakState.ValueType  # 2
NotCloaked: CloakState.ValueType  # 3
CloakedAllied: CloakState.ValueType  # 4
Global___CloakState: _TypeAlias = CloakState  # noqa: Y015

@_typing.final
class StartRaw(_message.Message):
    """
    Start
    """

    DESCRIPTOR: _descriptor.Descriptor

    MAP_SIZE_FIELD_NUMBER: _builtins.int
    PATHING_GRID_FIELD_NUMBER: _builtins.int
    TERRAIN_HEIGHT_FIELD_NUMBER: _builtins.int
    PLACEMENT_GRID_FIELD_NUMBER: _builtins.int
    PLAYABLE_AREA_FIELD_NUMBER: _builtins.int
    START_LOCATIONS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def map_size(self) -> _common_pb2.Size2DI:
        """Width and height of the map."""

    @_builtins.property
    def pathing_grid(self) -> _common_pb2.ImageData:
        """1 bit bitmap of the pathing grid."""

    @_builtins.property
    def terrain_height(self) -> _common_pb2.ImageData:
        """1 byte bitmap of the terrain height."""

    @_builtins.property
    def placement_grid(self) -> _common_pb2.ImageData:
        """1 bit bitmap of the building placement grid."""

    @_builtins.property
    def playable_area(self) -> _common_pb2.RectangleI:
        """The playable cells."""

    @_builtins.property
    def start_locations(self) -> _containers.RepeatedCompositeFieldContainer[_common_pb2.Point2D]:
        """Possible start locations for players."""

    def __init__(
        self,
        *,
        map_size: _common_pb2.Size2DI | None = ...,
        pathing_grid: _common_pb2.ImageData | None = ...,
        terrain_height: _common_pb2.ImageData | None = ...,
        placement_grid: _common_pb2.ImageData | None = ...,
        playable_area: _common_pb2.RectangleI | None = ...,
        start_locations: _abc.Iterable[_common_pb2.Point2D] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["map_size", b"map_size", "pathing_grid", b"pathing_grid", "placement_grid", b"placement_grid", "playable_area", b"playable_area", "terrain_height", b"terrain_height"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["map_size", b"map_size", "pathing_grid", b"pathing_grid", "placement_grid", b"placement_grid", "playable_area", b"playable_area", "start_locations", b"start_locations", "terrain_height", b"terrain_height"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StartRaw: _TypeAlias = StartRaw  # noqa: Y015

@_typing.final
class ObservationRaw(_message.Message):
    """
    Observation
    """

    DESCRIPTOR: _descriptor.Descriptor

    PLAYER_FIELD_NUMBER: _builtins.int
    UNITS_FIELD_NUMBER: _builtins.int
    MAP_STATE_FIELD_NUMBER: _builtins.int
    EVENT_FIELD_NUMBER: _builtins.int
    EFFECTS_FIELD_NUMBER: _builtins.int
    RADAR_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def player(self) -> Global___PlayerRaw: ...
    @_builtins.property
    def units(self) -> _containers.RepeatedCompositeFieldContainer[Global___Unit]: ...
    @_builtins.property
    def map_state(self) -> Global___MapState:
        """Fog of war, creep and so on. Board stuff that changes per frame."""

    @_builtins.property
    def event(self) -> Global___Event: ...
    @_builtins.property
    def effects(self) -> _containers.RepeatedCompositeFieldContainer[Global___Effect]: ...
    @_builtins.property
    def radar(self) -> _containers.RepeatedCompositeFieldContainer[Global___RadarRing]: ...
    def __init__(
        self,
        *,
        player: Global___PlayerRaw | None = ...,
        units: _abc.Iterable[Global___Unit] | None = ...,
        map_state: Global___MapState | None = ...,
        event: Global___Event | None = ...,
        effects: _abc.Iterable[Global___Effect] | None = ...,
        radar: _abc.Iterable[Global___RadarRing] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["event", b"event", "map_state", b"map_state", "player", b"player"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["effects", b"effects", "event", b"event", "map_state", b"map_state", "player", b"player", "radar", b"radar", "units", b"units"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ObservationRaw: _TypeAlias = ObservationRaw  # noqa: Y015

@_typing.final
class RadarRing(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    POS_FIELD_NUMBER: _builtins.int
    RADIUS_FIELD_NUMBER: _builtins.int
    radius: _builtins.float
    @_builtins.property
    def pos(self) -> _common_pb2.Point: ...
    def __init__(
        self,
        *,
        pos: _common_pb2.Point | None = ...,
        radius: _builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pos", b"pos", "radius", b"radius"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pos", b"pos", "radius", b"radius"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RadarRing: _TypeAlias = RadarRing  # noqa: Y015

@_typing.final
class PowerSource(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    POS_FIELD_NUMBER: _builtins.int
    RADIUS_FIELD_NUMBER: _builtins.int
    TAG_FIELD_NUMBER: _builtins.int
    radius: _builtins.float
    tag: _builtins.int
    @_builtins.property
    def pos(self) -> _common_pb2.Point: ...
    def __init__(
        self,
        *,
        pos: _common_pb2.Point | None = ...,
        radius: _builtins.float | None = ...,
        tag: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pos", b"pos", "radius", b"radius", "tag", b"tag"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pos", b"pos", "radius", b"radius", "tag", b"tag"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PowerSource: _TypeAlias = PowerSource  # noqa: Y015

@_typing.final
class PlayerRaw(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    POWER_SOURCES_FIELD_NUMBER: _builtins.int
    CAMERA_FIELD_NUMBER: _builtins.int
    UPGRADE_IDS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def power_sources(self) -> _containers.RepeatedCompositeFieldContainer[Global___PowerSource]: ...
    @_builtins.property
    def camera(self) -> _common_pb2.Point: ...
    @_builtins.property
    def upgrade_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """TODO: Add to UI observation?"""

    def __init__(
        self,
        *,
        power_sources: _abc.Iterable[Global___PowerSource] | None = ...,
        camera: _common_pb2.Point | None = ...,
        upgrade_ids: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["camera", b"camera"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["camera", b"camera", "power_sources", b"power_sources", "upgrade_ids", b"upgrade_ids"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PlayerRaw: _TypeAlias = PlayerRaw  # noqa: Y015

@_typing.final
class UnitOrder(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ABILITY_ID_FIELD_NUMBER: _builtins.int
    TARGET_WORLD_SPACE_POS_FIELD_NUMBER: _builtins.int
    TARGET_UNIT_TAG_FIELD_NUMBER: _builtins.int
    PROGRESS_FIELD_NUMBER: _builtins.int
    ability_id: _builtins.int
    target_unit_tag: _builtins.int
    progress: _builtins.float
    """Progress of train abilities. Range: [0.0, 1.0]"""
    @_builtins.property
    def target_world_space_pos(self) -> _common_pb2.Point: ...
    def __init__(
        self,
        *,
        ability_id: _builtins.int | None = ...,
        target_world_space_pos: _common_pb2.Point | None = ...,
        target_unit_tag: _builtins.int | None = ...,
        progress: _builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["ability_id", b"ability_id", "progress", b"progress", "target", b"target", "target_unit_tag", b"target_unit_tag", "target_world_space_pos", b"target_world_space_pos"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ability_id", b"ability_id", "progress", b"progress", "target", b"target", "target_unit_tag", b"target_unit_tag", "target_world_space_pos", b"target_world_space_pos"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_target: _TypeAlias = _typing.Literal["target_world_space_pos", "target_unit_tag"]  # noqa: Y015
    _WhichOneofArgType_target: _TypeAlias = _typing.Literal["target", b"target"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_target) -> _WhichOneofReturnType_target | None: ...

Global___UnitOrder: _TypeAlias = UnitOrder  # noqa: Y015

@_typing.final
class PassengerUnit(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TAG_FIELD_NUMBER: _builtins.int
    HEALTH_FIELD_NUMBER: _builtins.int
    HEALTH_MAX_FIELD_NUMBER: _builtins.int
    SHIELD_FIELD_NUMBER: _builtins.int
    SHIELD_MAX_FIELD_NUMBER: _builtins.int
    ENERGY_FIELD_NUMBER: _builtins.int
    ENERGY_MAX_FIELD_NUMBER: _builtins.int
    UNIT_TYPE_FIELD_NUMBER: _builtins.int
    tag: _builtins.int
    health: _builtins.float
    health_max: _builtins.float
    shield: _builtins.float
    shield_max: _builtins.float
    energy: _builtins.float
    energy_max: _builtins.float
    unit_type: _builtins.int
    def __init__(
        self,
        *,
        tag: _builtins.int | None = ...,
        health: _builtins.float | None = ...,
        health_max: _builtins.float | None = ...,
        shield: _builtins.float | None = ...,
        shield_max: _builtins.float | None = ...,
        energy: _builtins.float | None = ...,
        energy_max: _builtins.float | None = ...,
        unit_type: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["energy", b"energy", "energy_max", b"energy_max", "health", b"health", "health_max", b"health_max", "shield", b"shield", "shield_max", b"shield_max", "tag", b"tag", "unit_type", b"unit_type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["energy", b"energy", "energy_max", b"energy_max", "health", b"health", "health_max", b"health_max", "shield", b"shield", "shield_max", b"shield_max", "tag", b"tag", "unit_type", b"unit_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PassengerUnit: _TypeAlias = PassengerUnit  # noqa: Y015

@_typing.final
class RallyTarget(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    POINT_FIELD_NUMBER: _builtins.int
    TAG_FIELD_NUMBER: _builtins.int
    tag: _builtins.int
    """Only if it's targeting a unit."""
    @_builtins.property
    def point(self) -> _common_pb2.Point:
        """Will always be filled."""

    def __init__(
        self,
        *,
        point: _common_pb2.Point | None = ...,
        tag: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["point", b"point", "tag", b"tag"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["point", b"point", "tag", b"tag"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RallyTarget: _TypeAlias = RallyTarget  # noqa: Y015

@_typing.final
class Unit(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DISPLAY_TYPE_FIELD_NUMBER: _builtins.int
    ALLIANCE_FIELD_NUMBER: _builtins.int
    TAG_FIELD_NUMBER: _builtins.int
    UNIT_TYPE_FIELD_NUMBER: _builtins.int
    OWNER_FIELD_NUMBER: _builtins.int
    POS_FIELD_NUMBER: _builtins.int
    FACING_FIELD_NUMBER: _builtins.int
    RADIUS_FIELD_NUMBER: _builtins.int
    BUILD_PROGRESS_FIELD_NUMBER: _builtins.int
    CLOAK_FIELD_NUMBER: _builtins.int
    BUFF_IDS_FIELD_NUMBER: _builtins.int
    DETECT_RANGE_FIELD_NUMBER: _builtins.int
    RADAR_RANGE_FIELD_NUMBER: _builtins.int
    IS_SELECTED_FIELD_NUMBER: _builtins.int
    IS_ON_SCREEN_FIELD_NUMBER: _builtins.int
    IS_BLIP_FIELD_NUMBER: _builtins.int
    IS_POWERED_FIELD_NUMBER: _builtins.int
    IS_ACTIVE_FIELD_NUMBER: _builtins.int
    ATTACK_UPGRADE_LEVEL_FIELD_NUMBER: _builtins.int
    ARMOR_UPGRADE_LEVEL_FIELD_NUMBER: _builtins.int
    SHIELD_UPGRADE_LEVEL_FIELD_NUMBER: _builtins.int
    HEALTH_FIELD_NUMBER: _builtins.int
    HEALTH_MAX_FIELD_NUMBER: _builtins.int
    SHIELD_FIELD_NUMBER: _builtins.int
    SHIELD_MAX_FIELD_NUMBER: _builtins.int
    ENERGY_FIELD_NUMBER: _builtins.int
    ENERGY_MAX_FIELD_NUMBER: _builtins.int
    MINERAL_CONTENTS_FIELD_NUMBER: _builtins.int
    VESPENE_CONTENTS_FIELD_NUMBER: _builtins.int
    IS_FLYING_FIELD_NUMBER: _builtins.int
    IS_BURROWED_FIELD_NUMBER: _builtins.int
    IS_HALLUCINATION_FIELD_NUMBER: _builtins.int
    ORDERS_FIELD_NUMBER: _builtins.int
    ADD_ON_TAG_FIELD_NUMBER: _builtins.int
    PASSENGERS_FIELD_NUMBER: _builtins.int
    CARGO_SPACE_TAKEN_FIELD_NUMBER: _builtins.int
    CARGO_SPACE_MAX_FIELD_NUMBER: _builtins.int
    ASSIGNED_HARVESTERS_FIELD_NUMBER: _builtins.int
    IDEAL_HARVESTERS_FIELD_NUMBER: _builtins.int
    WEAPON_COOLDOWN_FIELD_NUMBER: _builtins.int
    ENGAGED_TARGET_TAG_FIELD_NUMBER: _builtins.int
    BUFF_DURATION_REMAIN_FIELD_NUMBER: _builtins.int
    BUFF_DURATION_MAX_FIELD_NUMBER: _builtins.int
    RALLY_TARGETS_FIELD_NUMBER: _builtins.int
    display_type: Global___DisplayType.ValueType
    """Fields are populated based on type/alliance"""
    alliance: Global___Alliance.ValueType
    tag: _builtins.int
    """Unique identifier for a unit"""
    unit_type: _builtins.int
    owner: _builtins.int
    facing: _builtins.float
    radius: _builtins.float
    build_progress: _builtins.float
    """Range: [0.0, 1.0]"""
    cloak: Global___CloakState.ValueType
    detect_range: _builtins.float
    radar_range: _builtins.float
    is_selected: _builtins.bool
    is_on_screen: _builtins.bool
    """Visible and within the camera frustrum."""
    is_blip: _builtins.bool
    """Detected by sensor tower"""
    is_powered: _builtins.bool
    is_active: _builtins.bool
    """Building is training/researching (ie animated)."""
    attack_upgrade_level: _builtins.int
    armor_upgrade_level: _builtins.int
    shield_upgrade_level: _builtins.int
    health: _builtins.float
    """Not populated for snapshots"""
    health_max: _builtins.float
    shield: _builtins.float
    shield_max: _builtins.float
    energy: _builtins.float
    energy_max: _builtins.float
    mineral_contents: _builtins.int
    vespene_contents: _builtins.int
    is_flying: _builtins.bool
    is_burrowed: _builtins.bool
    is_hallucination: _builtins.bool
    """Unit is your own or detected as a hallucination."""
    add_on_tag: _builtins.int
    cargo_space_taken: _builtins.int
    cargo_space_max: _builtins.int
    assigned_harvesters: _builtins.int
    ideal_harvesters: _builtins.int
    weapon_cooldown: _builtins.float
    engaged_target_tag: _builtins.int
    buff_duration_remain: _builtins.int
    """How long a buff or unit is still around (eg mule, broodling, chronoboost)."""
    buff_duration_max: _builtins.int
    """How long the buff or unit is still around (eg mule, broodling, chronoboost)."""
    @_builtins.property
    def pos(self) -> _common_pb2.Point: ...
    @_builtins.property
    def buff_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    @_builtins.property
    def orders(self) -> _containers.RepeatedCompositeFieldContainer[Global___UnitOrder]:
        """Not populated for enemies"""

    @_builtins.property
    def passengers(self) -> _containers.RepeatedCompositeFieldContainer[Global___PassengerUnit]: ...
    @_builtins.property
    def rally_targets(self) -> _containers.RepeatedCompositeFieldContainer[Global___RallyTarget]: ...
    def __init__(
        self,
        *,
        display_type: Global___DisplayType.ValueType | None = ...,
        alliance: Global___Alliance.ValueType | None = ...,
        tag: _builtins.int | None = ...,
        unit_type: _builtins.int | None = ...,
        owner: _builtins.int | None = ...,
        pos: _common_pb2.Point | None = ...,
        facing: _builtins.float | None = ...,
        radius: _builtins.float | None = ...,
        build_progress: _builtins.float | None = ...,
        cloak: Global___CloakState.ValueType | None = ...,
        buff_ids: _abc.Iterable[_builtins.int] | None = ...,
        detect_range: _builtins.float | None = ...,
        radar_range: _builtins.float | None = ...,
        is_selected: _builtins.bool | None = ...,
        is_on_screen: _builtins.bool | None = ...,
        is_blip: _builtins.bool | None = ...,
        is_powered: _builtins.bool | None = ...,
        is_active: _builtins.bool | None = ...,
        attack_upgrade_level: _builtins.int | None = ...,
        armor_upgrade_level: _builtins.int | None = ...,
        shield_upgrade_level: _builtins.int | None = ...,
        health: _builtins.float | None = ...,
        health_max: _builtins.float | None = ...,
        shield: _builtins.float | None = ...,
        shield_max: _builtins.float | None = ...,
        energy: _builtins.float | None = ...,
        energy_max: _builtins.float | None = ...,
        mineral_contents: _builtins.int | None = ...,
        vespene_contents: _builtins.int | None = ...,
        is_flying: _builtins.bool | None = ...,
        is_burrowed: _builtins.bool | None = ...,
        is_hallucination: _builtins.bool | None = ...,
        orders: _abc.Iterable[Global___UnitOrder] | None = ...,
        add_on_tag: _builtins.int | None = ...,
        passengers: _abc.Iterable[Global___PassengerUnit] | None = ...,
        cargo_space_taken: _builtins.int | None = ...,
        cargo_space_max: _builtins.int | None = ...,
        assigned_harvesters: _builtins.int | None = ...,
        ideal_harvesters: _builtins.int | None = ...,
        weapon_cooldown: _builtins.float | None = ...,
        engaged_target_tag: _builtins.int | None = ...,
        buff_duration_remain: _builtins.int | None = ...,
        buff_duration_max: _builtins.int | None = ...,
        rally_targets: _abc.Iterable[Global___RallyTarget] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["add_on_tag", b"add_on_tag", "alliance", b"alliance", "armor_upgrade_level", b"armor_upgrade_level", "assigned_harvesters", b"assigned_harvesters", "attack_upgrade_level", b"attack_upgrade_level", "buff_duration_max", b"buff_duration_max", "buff_duration_remain", b"buff_duration_remain", "build_progress", b"build_progress", "cargo_space_max", b"cargo_space_max", "cargo_space_taken", b"cargo_space_taken", "cloak", b"cloak", "detect_range", b"detect_range", "display_type", b"display_type", "energy", b"energy", "energy_max", b"energy_max", "engaged_target_tag", b"engaged_target_tag", "facing", b"facing", "health", b"health", "health_max", b"health_max", "ideal_harvesters", b"ideal_harvesters", "is_active", b"is_active", "is_blip", b"is_blip", "is_burrowed", b"is_burrowed", "is_flying", b"is_flying", "is_hallucination", b"is_hallucination", "is_on_screen", b"is_on_screen", "is_powered", b"is_powered", "is_selected", b"is_selected", "mineral_contents", b"mineral_contents", "owner", b"owner", "pos", b"pos", "radar_range", b"radar_range", "radius", b"radius", "shield", b"shield", "shield_max", b"shield_max", "shield_upgrade_level", b"shield_upgrade_level", "tag", b"tag", "unit_type", b"unit_type", "vespene_contents", b"vespene_contents", "weapon_cooldown", b"weapon_cooldown"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["add_on_tag", b"add_on_tag", "alliance", b"alliance", "armor_upgrade_level", b"armor_upgrade_level", "assigned_harvesters", b"assigned_harvesters", "attack_upgrade_level", b"attack_upgrade_level", "buff_duration_max", b"buff_duration_max", "buff_duration_remain", b"buff_duration_remain", "buff_ids", b"buff_ids", "build_progress", b"build_progress", "cargo_space_max", b"cargo_space_max", "cargo_space_taken", b"cargo_space_taken", "cloak", b"cloak", "detect_range", b"detect_range", "display_type", b"display_type", "energy", b"energy", "energy_max", b"energy_max", "engaged_target_tag", b"engaged_target_tag", "facing", b"facing", "health", b"health", "health_max", b"health_max", "ideal_harvesters", b"ideal_harvesters", "is_active", b"is_active", "is_blip", b"is_blip", "is_burrowed", b"is_burrowed", "is_flying", b"is_flying", "is_hallucination", b"is_hallucination", "is_on_screen", b"is_on_screen", "is_powered", b"is_powered", "is_selected", b"is_selected", "mineral_contents", b"mineral_contents", "orders", b"orders", "owner", b"owner", "passengers", b"passengers", "pos", b"pos", "radar_range", b"radar_range", "radius", b"radius", "rally_targets", b"rally_targets", "shield", b"shield", "shield_max", b"shield_max", "shield_upgrade_level", b"shield_upgrade_level", "tag", b"tag", "unit_type", b"unit_type", "vespene_contents", b"vespene_contents", "weapon_cooldown", b"weapon_cooldown"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Unit: _TypeAlias = Unit  # noqa: Y015

@_typing.final
class MapState(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VISIBILITY_FIELD_NUMBER: _builtins.int
    CREEP_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def visibility(self) -> _common_pb2.ImageData:
        """1 byte visibility layer."""

    @_builtins.property
    def creep(self) -> _common_pb2.ImageData:
        """1 bit creep layer."""

    def __init__(
        self,
        *,
        visibility: _common_pb2.ImageData | None = ...,
        creep: _common_pb2.ImageData | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["creep", b"creep", "visibility", b"visibility"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["creep", b"creep", "visibility", b"visibility"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MapState: _TypeAlias = MapState  # noqa: Y015

@_typing.final
class Event(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DEAD_UNITS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def dead_units(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        dead_units: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["dead_units", b"dead_units"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Event: _TypeAlias = Event  # noqa: Y015

@_typing.final
class Effect(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EFFECT_ID_FIELD_NUMBER: _builtins.int
    POS_FIELD_NUMBER: _builtins.int
    ALLIANCE_FIELD_NUMBER: _builtins.int
    OWNER_FIELD_NUMBER: _builtins.int
    RADIUS_FIELD_NUMBER: _builtins.int
    effect_id: _builtins.int
    alliance: Global___Alliance.ValueType
    owner: _builtins.int
    radius: _builtins.float
    @_builtins.property
    def pos(self) -> _containers.RepeatedCompositeFieldContainer[_common_pb2.Point2D]:
        """Effect may impact multiple locations. (eg. Lurker attack)"""

    def __init__(
        self,
        *,
        effect_id: _builtins.int | None = ...,
        pos: _abc.Iterable[_common_pb2.Point2D] | None = ...,
        alliance: Global___Alliance.ValueType | None = ...,
        owner: _builtins.int | None = ...,
        radius: _builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["alliance", b"alliance", "effect_id", b"effect_id", "owner", b"owner", "radius", b"radius"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["alliance", b"alliance", "effect_id", b"effect_id", "owner", b"owner", "pos", b"pos", "radius", b"radius"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Effect: _TypeAlias = Effect  # noqa: Y015

@_typing.final
class ActionRaw(_message.Message):
    """
    Action
    """

    DESCRIPTOR: _descriptor.Descriptor

    UNIT_COMMAND_FIELD_NUMBER: _builtins.int
    CAMERA_MOVE_FIELD_NUMBER: _builtins.int
    TOGGLE_AUTOCAST_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def unit_command(self) -> Global___ActionRawUnitCommand: ...
    @_builtins.property
    def camera_move(self) -> Global___ActionRawCameraMove: ...
    @_builtins.property
    def toggle_autocast(self) -> Global___ActionRawToggleAutocast: ...
    def __init__(
        self,
        *,
        unit_command: Global___ActionRawUnitCommand | None = ...,
        camera_move: Global___ActionRawCameraMove | None = ...,
        toggle_autocast: Global___ActionRawToggleAutocast | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["action", b"action", "camera_move", b"camera_move", "toggle_autocast", b"toggle_autocast", "unit_command", b"unit_command"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["action", b"action", "camera_move", b"camera_move", "toggle_autocast", b"toggle_autocast", "unit_command", b"unit_command"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_action: _TypeAlias = _typing.Literal["unit_command", "camera_move", "toggle_autocast"]  # noqa: Y015
    _WhichOneofArgType_action: _TypeAlias = _typing.Literal["action", b"action"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_action) -> _WhichOneofReturnType_action | None: ...

Global___ActionRaw: _TypeAlias = ActionRaw  # noqa: Y015

@_typing.final
class ActionRawUnitCommand(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ABILITY_ID_FIELD_NUMBER: _builtins.int
    TARGET_WORLD_SPACE_POS_FIELD_NUMBER: _builtins.int
    TARGET_UNIT_TAG_FIELD_NUMBER: _builtins.int
    UNIT_TAGS_FIELD_NUMBER: _builtins.int
    QUEUE_COMMAND_FIELD_NUMBER: _builtins.int
    ability_id: _builtins.int
    target_unit_tag: _builtins.int
    queue_command: _builtins.bool
    @_builtins.property
    def target_world_space_pos(self) -> _common_pb2.Point2D: ...
    @_builtins.property
    def unit_tags(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        ability_id: _builtins.int | None = ...,
        target_world_space_pos: _common_pb2.Point2D | None = ...,
        target_unit_tag: _builtins.int | None = ...,
        unit_tags: _abc.Iterable[_builtins.int] | None = ...,
        queue_command: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["ability_id", b"ability_id", "queue_command", b"queue_command", "target", b"target", "target_unit_tag", b"target_unit_tag", "target_world_space_pos", b"target_world_space_pos"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ability_id", b"ability_id", "queue_command", b"queue_command", "target", b"target", "target_unit_tag", b"target_unit_tag", "target_world_space_pos", b"target_world_space_pos", "unit_tags", b"unit_tags"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_target: _TypeAlias = _typing.Literal["target_world_space_pos", "target_unit_tag"]  # noqa: Y015
    _WhichOneofArgType_target: _TypeAlias = _typing.Literal["target", b"target"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_target) -> _WhichOneofReturnType_target | None: ...

Global___ActionRawUnitCommand: _TypeAlias = ActionRawUnitCommand  # noqa: Y015

@_typing.final
class ActionRawCameraMove(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CENTER_WORLD_SPACE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def center_world_space(self) -> _common_pb2.Point: ...
    def __init__(
        self,
        *,
        center_world_space: _common_pb2.Point | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["center_world_space", b"center_world_space"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["center_world_space", b"center_world_space"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ActionRawCameraMove: _TypeAlias = ActionRawCameraMove  # noqa: Y015

@_typing.final
class ActionRawToggleAutocast(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ABILITY_ID_FIELD_NUMBER: _builtins.int
    UNIT_TAGS_FIELD_NUMBER: _builtins.int
    ability_id: _builtins.int
    @_builtins.property
    def unit_tags(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        ability_id: _builtins.int | None = ...,
        unit_tags: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["ability_id", b"ability_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ability_id", b"ability_id", "unit_tags", b"unit_tags"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ActionRawToggleAutocast: _TypeAlias = ActionRawToggleAutocast  # noqa: Y015
