"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Score(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _ScoreType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _ScoreTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Score._ScoreType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        Curriculum: Score._ScoreType.ValueType  # 1
        """map generated score (from curriculum maps with special scoring)"""
        Melee: Score._ScoreType.ValueType  # 2
        """summation of in-progress and current units/buildings value + minerals + vespene"""

    class ScoreType(_ScoreType, metaclass=_ScoreTypeEnumTypeWrapper): ...
    Curriculum: Score.ScoreType.ValueType  # 1
    """map generated score (from curriculum maps with special scoring)"""
    Melee: Score.ScoreType.ValueType  # 2
    """summation of in-progress and current units/buildings value + minerals + vespene"""

    SCORE_TYPE_FIELD_NUMBER: _builtins.int
    SCORE_FIELD_NUMBER: _builtins.int
    SCORE_DETAILS_FIELD_NUMBER: _builtins.int
    score_type: Global___Score.ScoreType.ValueType
    score: _builtins.int
    """Note: check score_type to know whether this is a melee score or curriculum score"""
    @_builtins.property
    def score_details(self) -> Global___ScoreDetails: ...
    def __init__(
        self,
        *,
        score_type: Global___Score.ScoreType.ValueType | None = ...,
        score: _builtins.int | None = ...,
        score_details: Global___ScoreDetails | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["score", b"score", "score_details", b"score_details", "score_type", b"score_type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["score", b"score", "score_details", b"score_details", "score_type", b"score_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Score: _TypeAlias = Score  # noqa: Y015

@_typing.final
class CategoryScoreDetails(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NONE_FIELD_NUMBER: _builtins.int
    ARMY_FIELD_NUMBER: _builtins.int
    ECONOMY_FIELD_NUMBER: _builtins.int
    TECHNOLOGY_FIELD_NUMBER: _builtins.int
    UPGRADE_FIELD_NUMBER: _builtins.int
    none: _builtins.float
    """Used when no other category is configured in game data"""
    army: _builtins.float
    economy: _builtins.float
    technology: _builtins.float
    upgrade: _builtins.float
    def __init__(
        self,
        *,
        none: _builtins.float | None = ...,
        army: _builtins.float | None = ...,
        economy: _builtins.float | None = ...,
        technology: _builtins.float | None = ...,
        upgrade: _builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["army", b"army", "economy", b"economy", "none", b"none", "technology", b"technology", "upgrade", b"upgrade"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["army", b"army", "economy", b"economy", "none", b"none", "technology", b"technology", "upgrade", b"upgrade"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CategoryScoreDetails: _TypeAlias = CategoryScoreDetails  # noqa: Y015

@_typing.final
class VitalScoreDetails(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LIFE_FIELD_NUMBER: _builtins.int
    SHIELDS_FIELD_NUMBER: _builtins.int
    ENERGY_FIELD_NUMBER: _builtins.int
    life: _builtins.float
    shields: _builtins.float
    energy: _builtins.float
    def __init__(
        self,
        *,
        life: _builtins.float | None = ...,
        shields: _builtins.float | None = ...,
        energy: _builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["energy", b"energy", "life", b"life", "shields", b"shields"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["energy", b"energy", "life", b"life", "shields", b"shields"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___VitalScoreDetails: _TypeAlias = VitalScoreDetails  # noqa: Y015

@_typing.final
class ScoreDetails(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    IDLE_PRODUCTION_TIME_FIELD_NUMBER: _builtins.int
    IDLE_WORKER_TIME_FIELD_NUMBER: _builtins.int
    TOTAL_VALUE_UNITS_FIELD_NUMBER: _builtins.int
    TOTAL_VALUE_STRUCTURES_FIELD_NUMBER: _builtins.int
    KILLED_VALUE_UNITS_FIELD_NUMBER: _builtins.int
    KILLED_VALUE_STRUCTURES_FIELD_NUMBER: _builtins.int
    COLLECTED_MINERALS_FIELD_NUMBER: _builtins.int
    COLLECTED_VESPENE_FIELD_NUMBER: _builtins.int
    COLLECTION_RATE_MINERALS_FIELD_NUMBER: _builtins.int
    COLLECTION_RATE_VESPENE_FIELD_NUMBER: _builtins.int
    SPENT_MINERALS_FIELD_NUMBER: _builtins.int
    SPENT_VESPENE_FIELD_NUMBER: _builtins.int
    FOOD_USED_FIELD_NUMBER: _builtins.int
    KILLED_MINERALS_FIELD_NUMBER: _builtins.int
    KILLED_VESPENE_FIELD_NUMBER: _builtins.int
    LOST_MINERALS_FIELD_NUMBER: _builtins.int
    LOST_VESPENE_FIELD_NUMBER: _builtins.int
    FRIENDLY_FIRE_MINERALS_FIELD_NUMBER: _builtins.int
    FRIENDLY_FIRE_VESPENE_FIELD_NUMBER: _builtins.int
    USED_MINERALS_FIELD_NUMBER: _builtins.int
    USED_VESPENE_FIELD_NUMBER: _builtins.int
    TOTAL_USED_MINERALS_FIELD_NUMBER: _builtins.int
    TOTAL_USED_VESPENE_FIELD_NUMBER: _builtins.int
    TOTAL_DAMAGE_DEALT_FIELD_NUMBER: _builtins.int
    TOTAL_DAMAGE_TAKEN_FIELD_NUMBER: _builtins.int
    TOTAL_HEALED_FIELD_NUMBER: _builtins.int
    CURRENT_APM_FIELD_NUMBER: _builtins.int
    CURRENT_EFFECTIVE_APM_FIELD_NUMBER: _builtins.int
    idle_production_time: _builtins.float
    """Sum of time any available structure able to produce a unit is not. The time stacks, as in, three idle barracks will increase idle_production_time three times quicker than just one."""
    idle_worker_time: _builtins.float
    """Sum of time any worker is not mining. Note a worker building is not idle and three idle workers will increase this value three times quicker than just one."""
    total_value_units: _builtins.float
    """Sum of minerals and vespene spent on completed units."""
    total_value_structures: _builtins.float
    """Sum of minerals and vespene spent on completed structures."""
    killed_value_units: _builtins.float
    """Sum of minerals and vespene of units, belonging to the opponent, that the player has destroyed."""
    killed_value_structures: _builtins.float
    """Sum of minerals and vespene of structures, belonging to the opponent, that the player has destroyed."""
    collected_minerals: _builtins.float
    """Sum of minerals collected by the player."""
    collected_vespene: _builtins.float
    """Sum of vespene collected by the player."""
    collection_rate_minerals: _builtins.float
    """Estimated income of minerals over the next minute based on the players current income. The unit is minerals per minute."""
    collection_rate_vespene: _builtins.float
    """Estimated income of vespene over the next minute based on the players current income. The unit is vespene per minute."""
    spent_minerals: _builtins.float
    """Sum of spent minerals at the moment it is spent. For example, this number is incremented by 50 the moment an scv is queued in a command center.  It is decremented by 50 if that unit is canceled."""
    spent_vespene: _builtins.float
    """Sum of spent vespene at the moment it is spent. For example, this number is incremented by 50 when a reaper is queued but decremented by 50 if it is canceled."""
    current_apm: _builtins.float
    """Recent raw APM."""
    current_effective_apm: _builtins.float
    """Recent effective APM."""
    @_builtins.property
    def food_used(self) -> Global___CategoryScoreDetails:
        """The following entries contains floating point values for the following catgories:
          none - There is no category defined in game data.
          army - This category includes all military units but not workers.
          economy - This category contains town halls, supply structures, vespene buildings and workers.
          technology - This category is any structure that produces units or upgrades, Barracks and Engineering Bays both fall in this category, for example.
          upgrade - This category is upgrades such as warp gate or weapons upgrades.

        Sum of food, or supply, utilized in the categories above.
        """

    @_builtins.property
    def killed_minerals(self) -> Global___CategoryScoreDetails:
        """Sum of enemies catagories destroyed in minerals."""

    @_builtins.property
    def killed_vespene(self) -> Global___CategoryScoreDetails:
        """Sum of enemies catagories destroyed in vespene."""

    @_builtins.property
    def lost_minerals(self) -> Global___CategoryScoreDetails:
        """ Sum of lost minerals for the player in each category."""

    @_builtins.property
    def lost_vespene(self) -> Global___CategoryScoreDetails:
        """Sum of lost vespene for the player in each category."""

    @_builtins.property
    def friendly_fire_minerals(self) -> Global___CategoryScoreDetails:
        """Sum of the lost minerals via destroying the players own units/buildings."""

    @_builtins.property
    def friendly_fire_vespene(self) -> Global___CategoryScoreDetails:
        """Sum of the lost vespene via destroying the players own units/buildings."""

    @_builtins.property
    def used_minerals(self) -> Global___CategoryScoreDetails:
        """Sum of used minerals for the player in each category for each existing unit or upgrade. Therefore if a unit died worth 50 mierals this number will be decremented by 50."""

    @_builtins.property
    def used_vespene(self) -> Global___CategoryScoreDetails:
        """Sum of used vespene for the player in each category. Therefore if a unit died worth 50 vespene this number will be decremented by 50."""

    @_builtins.property
    def total_used_minerals(self) -> Global___CategoryScoreDetails:
        """Sum of used minerals throughout the entire game for each category. Unliked used_minerals, this value is never decremented."""

    @_builtins.property
    def total_used_vespene(self) -> Global___CategoryScoreDetails:
        """Sum of used vespene throughout the entire game for each category. Unliked used_vespene, this value is never decremented."""

    @_builtins.property
    def total_damage_dealt(self) -> Global___VitalScoreDetails:
        """Sum of damage dealt to the player's opponent for each category."""

    @_builtins.property
    def total_damage_taken(self) -> Global___VitalScoreDetails:
        """Sum of damage taken by the player for each category."""

    @_builtins.property
    def total_healed(self) -> Global___VitalScoreDetails:
        """Sum of health healed by the player. Note that technology can be healed (by queens) or repaired (by scvs)."""

    def __init__(
        self,
        *,
        idle_production_time: _builtins.float | None = ...,
        idle_worker_time: _builtins.float | None = ...,
        total_value_units: _builtins.float | None = ...,
        total_value_structures: _builtins.float | None = ...,
        killed_value_units: _builtins.float | None = ...,
        killed_value_structures: _builtins.float | None = ...,
        collected_minerals: _builtins.float | None = ...,
        collected_vespene: _builtins.float | None = ...,
        collection_rate_minerals: _builtins.float | None = ...,
        collection_rate_vespene: _builtins.float | None = ...,
        spent_minerals: _builtins.float | None = ...,
        spent_vespene: _builtins.float | None = ...,
        food_used: Global___CategoryScoreDetails | None = ...,
        killed_minerals: Global___CategoryScoreDetails | None = ...,
        killed_vespene: Global___CategoryScoreDetails | None = ...,
        lost_minerals: Global___CategoryScoreDetails | None = ...,
        lost_vespene: Global___CategoryScoreDetails | None = ...,
        friendly_fire_minerals: Global___CategoryScoreDetails | None = ...,
        friendly_fire_vespene: Global___CategoryScoreDetails | None = ...,
        used_minerals: Global___CategoryScoreDetails | None = ...,
        used_vespene: Global___CategoryScoreDetails | None = ...,
        total_used_minerals: Global___CategoryScoreDetails | None = ...,
        total_used_vespene: Global___CategoryScoreDetails | None = ...,
        total_damage_dealt: Global___VitalScoreDetails | None = ...,
        total_damage_taken: Global___VitalScoreDetails | None = ...,
        total_healed: Global___VitalScoreDetails | None = ...,
        current_apm: _builtins.float | None = ...,
        current_effective_apm: _builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["collected_minerals", b"collected_minerals", "collected_vespene", b"collected_vespene", "collection_rate_minerals", b"collection_rate_minerals", "collection_rate_vespene", b"collection_rate_vespene", "current_apm", b"current_apm", "current_effective_apm", b"current_effective_apm", "food_used", b"food_used", "friendly_fire_minerals", b"friendly_fire_minerals", "friendly_fire_vespene", b"friendly_fire_vespene", "idle_production_time", b"idle_production_time", "idle_worker_time", b"idle_worker_time", "killed_minerals", b"killed_minerals", "killed_value_structures", b"killed_value_structures", "killed_value_units", b"killed_value_units", "killed_vespene", b"killed_vespene", "lost_minerals", b"lost_minerals", "lost_vespene", b"lost_vespene", "spent_minerals", b"spent_minerals", "spent_vespene", b"spent_vespene", "total_damage_dealt", b"total_damage_dealt", "total_damage_taken", b"total_damage_taken", "total_healed", b"total_healed", "total_used_minerals", b"total_used_minerals", "total_used_vespene", b"total_used_vespene", "total_value_structures", b"total_value_structures", "total_value_units", b"total_value_units", "used_minerals", b"used_minerals", "used_vespene", b"used_vespene"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["collected_minerals", b"collected_minerals", "collected_vespene", b"collected_vespene", "collection_rate_minerals", b"collection_rate_minerals", "collection_rate_vespene", b"collection_rate_vespene", "current_apm", b"current_apm", "current_effective_apm", b"current_effective_apm", "food_used", b"food_used", "friendly_fire_minerals", b"friendly_fire_minerals", "friendly_fire_vespene", b"friendly_fire_vespene", "idle_production_time", b"idle_production_time", "idle_worker_time", b"idle_worker_time", "killed_minerals", b"killed_minerals", "killed_value_structures", b"killed_value_structures", "killed_value_units", b"killed_value_units", "killed_vespene", b"killed_vespene", "lost_minerals", b"lost_minerals", "lost_vespene", b"lost_vespene", "spent_minerals", b"spent_minerals", "spent_vespene", b"spent_vespene", "total_damage_dealt", b"total_damage_dealt", "total_damage_taken", b"total_damage_taken", "total_healed", b"total_healed", "total_used_minerals", b"total_used_minerals", "total_used_vespene", b"total_used_vespene", "total_value_structures", b"total_value_structures", "total_value_units", b"total_value_units", "used_minerals", b"used_minerals", "used_vespene", b"used_vespene"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ScoreDetails: _TypeAlias = ScoreDetails  # noqa: Y015
