"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from s2clientprotocol import common_pb2 as _common_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ObservationFeatureLayer(_message.Message):
    """
    Observation - Feature Layer
    """

    DESCRIPTOR: _descriptor.Descriptor

    RENDERS_FIELD_NUMBER: _builtins.int
    MINIMAP_RENDERS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def renders(self) -> Global___FeatureLayers: ...
    @_builtins.property
    def minimap_renders(self) -> Global___FeatureLayersMinimap: ...
    def __init__(
        self,
        *,
        renders: Global___FeatureLayers | None = ...,
        minimap_renders: Global___FeatureLayersMinimap | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["minimap_renders", b"minimap_renders", "renders", b"renders"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["minimap_renders", b"minimap_renders", "renders", b"renders"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ObservationFeatureLayer: _TypeAlias = ObservationFeatureLayer  # noqa: Y015

@_typing.final
class FeatureLayers(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HEIGHT_MAP_FIELD_NUMBER: _builtins.int
    VISIBILITY_MAP_FIELD_NUMBER: _builtins.int
    CREEP_FIELD_NUMBER: _builtins.int
    POWER_FIELD_NUMBER: _builtins.int
    PLAYER_ID_FIELD_NUMBER: _builtins.int
    UNIT_TYPE_FIELD_NUMBER: _builtins.int
    SELECTED_FIELD_NUMBER: _builtins.int
    UNIT_HIT_POINTS_FIELD_NUMBER: _builtins.int
    UNIT_HIT_POINTS_RATIO_FIELD_NUMBER: _builtins.int
    UNIT_ENERGY_FIELD_NUMBER: _builtins.int
    UNIT_ENERGY_RATIO_FIELD_NUMBER: _builtins.int
    UNIT_SHIELDS_FIELD_NUMBER: _builtins.int
    UNIT_SHIELDS_RATIO_FIELD_NUMBER: _builtins.int
    PLAYER_RELATIVE_FIELD_NUMBER: _builtins.int
    UNIT_DENSITY_AA_FIELD_NUMBER: _builtins.int
    UNIT_DENSITY_FIELD_NUMBER: _builtins.int
    EFFECTS_FIELD_NUMBER: _builtins.int
    HALLUCINATIONS_FIELD_NUMBER: _builtins.int
    CLOAKED_FIELD_NUMBER: _builtins.int
    BLIP_FIELD_NUMBER: _builtins.int
    BUFFS_FIELD_NUMBER: _builtins.int
    BUFF_DURATION_FIELD_NUMBER: _builtins.int
    ACTIVE_FIELD_NUMBER: _builtins.int
    BUILD_PROGRESS_FIELD_NUMBER: _builtins.int
    BUILDABLE_FIELD_NUMBER: _builtins.int
    PATHABLE_FIELD_NUMBER: _builtins.int
    PLACEHOLDER_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def height_map(self) -> _common_pb2.ImageData:
        """uint8. Terrain height. World space units of [-200, 200] encoded into [0, 255]."""

    @_builtins.property
    def visibility_map(self) -> _common_pb2.ImageData:
        """uint8. 0=Hidden, 1=Fogged, 2=Visible, 3=FullHidden"""

    @_builtins.property
    def creep(self) -> _common_pb2.ImageData:
        """1-bit. Zerg creep."""

    @_builtins.property
    def power(self) -> _common_pb2.ImageData:
        """1-bit. Protoss power."""

    @_builtins.property
    def player_id(self) -> _common_pb2.ImageData:
        """uint8. Participants: [1, 15] Neutral: 16"""

    @_builtins.property
    def unit_type(self) -> _common_pb2.ImageData:
        """int32. Unique identifier for type of unit."""

    @_builtins.property
    def selected(self) -> _common_pb2.ImageData:
        """1-bit. Selected units."""

    @_builtins.property
    def unit_hit_points(self) -> _common_pb2.ImageData:
        """int32."""

    @_builtins.property
    def unit_hit_points_ratio(self) -> _common_pb2.ImageData:
        """uint8. Ratio of current health to max health. [0%, 100%] encoded into [0, 255]."""

    @_builtins.property
    def unit_energy(self) -> _common_pb2.ImageData:
        """int32."""

    @_builtins.property
    def unit_energy_ratio(self) -> _common_pb2.ImageData:
        """uint8. Ratio of current energy to max energy. [0%, 100%] encoded into [0, 255]."""

    @_builtins.property
    def unit_shields(self) -> _common_pb2.ImageData:
        """int32."""

    @_builtins.property
    def unit_shields_ratio(self) -> _common_pb2.ImageData:
        """uint8. Ratio of current shields to max shields. [0%, 100%] encoded into [0, 255]."""

    @_builtins.property
    def player_relative(self) -> _common_pb2.ImageData:
        """uint8. See "Alliance" enum in raw.proto. Range: [1, 4]"""

    @_builtins.property
    def unit_density_aa(self) -> _common_pb2.ImageData:
        """uint8. Density of units overlapping a pixel, anti-aliased. [0.0, 16.0f] encoded into [0, 255]."""

    @_builtins.property
    def unit_density(self) -> _common_pb2.ImageData:
        """uint8. Count of units overlapping a pixel."""

    @_builtins.property
    def effects(self) -> _common_pb2.ImageData:
        """uint8. Visuals of persistent abilities. (eg. Psistorm)"""

    @_builtins.property
    def hallucinations(self) -> _common_pb2.ImageData:
        """1-bit. Whether the unit here is a hallucination."""

    @_builtins.property
    def cloaked(self) -> _common_pb2.ImageData:
        """1-bit. Whether the unit here is cloaked. Hidden units will show up too, but with less details in other layers."""

    @_builtins.property
    def blip(self) -> _common_pb2.ImageData:
        """1-bit. Whether the unit here is a blip."""

    @_builtins.property
    def buffs(self) -> _common_pb2.ImageData:
        """int32. One of the buffs applied to this unit. Extras are ignored."""

    @_builtins.property
    def buff_duration(self) -> _common_pb2.ImageData:
        """uint8. Ratio of buff remaining. [0%, 100%] encoded into [0, 255]."""

    @_builtins.property
    def active(self) -> _common_pb2.ImageData:
        """1-bit. Whether the unit here is active."""

    @_builtins.property
    def build_progress(self) -> _common_pb2.ImageData:
        """uint8. How far along the building is building something. [0%, 100%] encoded into [0, 255]."""

    @_builtins.property
    def buildable(self) -> _common_pb2.ImageData:
        """1-bit. Whether a building can be built here."""

    @_builtins.property
    def pathable(self) -> _common_pb2.ImageData:
        """1-bit. Whether a unit can walk here."""

    @_builtins.property
    def placeholder(self) -> _common_pb2.ImageData:
        """1-bit. Whether the unit here is a placeholder building to be constructed."""

    def __init__(
        self,
        *,
        height_map: _common_pb2.ImageData | None = ...,
        visibility_map: _common_pb2.ImageData | None = ...,
        creep: _common_pb2.ImageData | None = ...,
        power: _common_pb2.ImageData | None = ...,
        player_id: _common_pb2.ImageData | None = ...,
        unit_type: _common_pb2.ImageData | None = ...,
        selected: _common_pb2.ImageData | None = ...,
        unit_hit_points: _common_pb2.ImageData | None = ...,
        unit_hit_points_ratio: _common_pb2.ImageData | None = ...,
        unit_energy: _common_pb2.ImageData | None = ...,
        unit_energy_ratio: _common_pb2.ImageData | None = ...,
        unit_shields: _common_pb2.ImageData | None = ...,
        unit_shields_ratio: _common_pb2.ImageData | None = ...,
        player_relative: _common_pb2.ImageData | None = ...,
        unit_density_aa: _common_pb2.ImageData | None = ...,
        unit_density: _common_pb2.ImageData | None = ...,
        effects: _common_pb2.ImageData | None = ...,
        hallucinations: _common_pb2.ImageData | None = ...,
        cloaked: _common_pb2.ImageData | None = ...,
        blip: _common_pb2.ImageData | None = ...,
        buffs: _common_pb2.ImageData | None = ...,
        buff_duration: _common_pb2.ImageData | None = ...,
        active: _common_pb2.ImageData | None = ...,
        build_progress: _common_pb2.ImageData | None = ...,
        buildable: _common_pb2.ImageData | None = ...,
        pathable: _common_pb2.ImageData | None = ...,
        placeholder: _common_pb2.ImageData | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["active", b"active", "blip", b"blip", "buff_duration", b"buff_duration", "buffs", b"buffs", "build_progress", b"build_progress", "buildable", b"buildable", "cloaked", b"cloaked", "creep", b"creep", "effects", b"effects", "hallucinations", b"hallucinations", "height_map", b"height_map", "pathable", b"pathable", "placeholder", b"placeholder", "player_id", b"player_id", "player_relative", b"player_relative", "power", b"power", "selected", b"selected", "unit_density", b"unit_density", "unit_density_aa", b"unit_density_aa", "unit_energy", b"unit_energy", "unit_energy_ratio", b"unit_energy_ratio", "unit_hit_points", b"unit_hit_points", "unit_hit_points_ratio", b"unit_hit_points_ratio", "unit_shields", b"unit_shields", "unit_shields_ratio", b"unit_shields_ratio", "unit_type", b"unit_type", "visibility_map", b"visibility_map"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["active", b"active", "blip", b"blip", "buff_duration", b"buff_duration", "buffs", b"buffs", "build_progress", b"build_progress", "buildable", b"buildable", "cloaked", b"cloaked", "creep", b"creep", "effects", b"effects", "hallucinations", b"hallucinations", "height_map", b"height_map", "pathable", b"pathable", "placeholder", b"placeholder", "player_id", b"player_id", "player_relative", b"player_relative", "power", b"power", "selected", b"selected", "unit_density", b"unit_density", "unit_density_aa", b"unit_density_aa", "unit_energy", b"unit_energy", "unit_energy_ratio", b"unit_energy_ratio", "unit_hit_points", b"unit_hit_points", "unit_hit_points_ratio", b"unit_hit_points_ratio", "unit_shields", b"unit_shields", "unit_shields_ratio", b"unit_shields_ratio", "unit_type", b"unit_type", "visibility_map", b"visibility_map"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___FeatureLayers: _TypeAlias = FeatureLayers  # noqa: Y015

@_typing.final
class FeatureLayersMinimap(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HEIGHT_MAP_FIELD_NUMBER: _builtins.int
    VISIBILITY_MAP_FIELD_NUMBER: _builtins.int
    CREEP_FIELD_NUMBER: _builtins.int
    CAMERA_FIELD_NUMBER: _builtins.int
    PLAYER_ID_FIELD_NUMBER: _builtins.int
    PLAYER_RELATIVE_FIELD_NUMBER: _builtins.int
    SELECTED_FIELD_NUMBER: _builtins.int
    ALERTS_FIELD_NUMBER: _builtins.int
    BUILDABLE_FIELD_NUMBER: _builtins.int
    PATHABLE_FIELD_NUMBER: _builtins.int
    UNIT_TYPE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def height_map(self) -> _common_pb2.ImageData:
        """uint8. Terrain height. World space units of [-200, 200] encoded into [0, 255]."""

    @_builtins.property
    def visibility_map(self) -> _common_pb2.ImageData:
        """uint8. 0=Hidden, 1=Fogged, 2=Visible, 3=FullHidden"""

    @_builtins.property
    def creep(self) -> _common_pb2.ImageData:
        """1-bit. Zerg creep."""

    @_builtins.property
    def camera(self) -> _common_pb2.ImageData:
        """1-bit. Area covered by the camera."""

    @_builtins.property
    def player_id(self) -> _common_pb2.ImageData:
        """uint8. Participants: [1, 15] Neutral: 16"""

    @_builtins.property
    def player_relative(self) -> _common_pb2.ImageData:
        """uint8. See "Alliance" enum in raw.proto. Range: [1, 4]"""

    @_builtins.property
    def selected(self) -> _common_pb2.ImageData:
        """1-bit. Selected units."""

    @_builtins.property
    def alerts(self) -> _common_pb2.ImageData:
        """1-bit. Shows 'UnitAttacked' alert location."""

    @_builtins.property
    def buildable(self) -> _common_pb2.ImageData:
        """1-bit. Whether a building can be built here."""

    @_builtins.property
    def pathable(self) -> _common_pb2.ImageData:
        """1-bit. Whether a unit can walk here."""

    @_builtins.property
    def unit_type(self) -> _common_pb2.ImageData:
        """Cheat layers, enable with SpatialCameraSetup.allow_cheating_layers.
        int32. Unique identifier for type of unit.
        """

    def __init__(
        self,
        *,
        height_map: _common_pb2.ImageData | None = ...,
        visibility_map: _common_pb2.ImageData | None = ...,
        creep: _common_pb2.ImageData | None = ...,
        camera: _common_pb2.ImageData | None = ...,
        player_id: _common_pb2.ImageData | None = ...,
        player_relative: _common_pb2.ImageData | None = ...,
        selected: _common_pb2.ImageData | None = ...,
        alerts: _common_pb2.ImageData | None = ...,
        buildable: _common_pb2.ImageData | None = ...,
        pathable: _common_pb2.ImageData | None = ...,
        unit_type: _common_pb2.ImageData | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["alerts", b"alerts", "buildable", b"buildable", "camera", b"camera", "creep", b"creep", "height_map", b"height_map", "pathable", b"pathable", "player_id", b"player_id", "player_relative", b"player_relative", "selected", b"selected", "unit_type", b"unit_type", "visibility_map", b"visibility_map"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["alerts", b"alerts", "buildable", b"buildable", "camera", b"camera", "creep", b"creep", "height_map", b"height_map", "pathable", b"pathable", "player_id", b"player_id", "player_relative", b"player_relative", "selected", b"selected", "unit_type", b"unit_type", "visibility_map", b"visibility_map"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___FeatureLayersMinimap: _TypeAlias = FeatureLayersMinimap  # noqa: Y015

@_typing.final
class ObservationRender(_message.Message):
    """
    Observation - Rendered
    """

    DESCRIPTOR: _descriptor.Descriptor

    MAP_FIELD_NUMBER: _builtins.int
    MINIMAP_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def map(self) -> _common_pb2.ImageData: ...
    @_builtins.property
    def minimap(self) -> _common_pb2.ImageData: ...
    def __init__(
        self,
        *,
        map: _common_pb2.ImageData | None = ...,
        minimap: _common_pb2.ImageData | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["map", b"map", "minimap", b"minimap"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["map", b"map", "minimap", b"minimap"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ObservationRender: _TypeAlias = ObservationRender  # noqa: Y015

@_typing.final
class ActionSpatial(_message.Message):
    """
    Action
    """

    DESCRIPTOR: _descriptor.Descriptor

    UNIT_COMMAND_FIELD_NUMBER: _builtins.int
    CAMERA_MOVE_FIELD_NUMBER: _builtins.int
    UNIT_SELECTION_POINT_FIELD_NUMBER: _builtins.int
    UNIT_SELECTION_RECT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def unit_command(self) -> Global___ActionSpatialUnitCommand: ...
    @_builtins.property
    def camera_move(self) -> Global___ActionSpatialCameraMove: ...
    @_builtins.property
    def unit_selection_point(self) -> Global___ActionSpatialUnitSelectionPoint: ...
    @_builtins.property
    def unit_selection_rect(self) -> Global___ActionSpatialUnitSelectionRect: ...
    def __init__(
        self,
        *,
        unit_command: Global___ActionSpatialUnitCommand | None = ...,
        camera_move: Global___ActionSpatialCameraMove | None = ...,
        unit_selection_point: Global___ActionSpatialUnitSelectionPoint | None = ...,
        unit_selection_rect: Global___ActionSpatialUnitSelectionRect | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["action", b"action", "camera_move", b"camera_move", "unit_command", b"unit_command", "unit_selection_point", b"unit_selection_point", "unit_selection_rect", b"unit_selection_rect"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["action", b"action", "camera_move", b"camera_move", "unit_command", b"unit_command", "unit_selection_point", b"unit_selection_point", "unit_selection_rect", b"unit_selection_rect"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_action: _TypeAlias = _typing.Literal["unit_command", "camera_move", "unit_selection_point", "unit_selection_rect"]  # noqa: Y015
    _WhichOneofArgType_action: _TypeAlias = _typing.Literal["action", b"action"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_action) -> _WhichOneofReturnType_action | None: ...

Global___ActionSpatial: _TypeAlias = ActionSpatial  # noqa: Y015

@_typing.final
class ActionSpatialUnitCommand(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ABILITY_ID_FIELD_NUMBER: _builtins.int
    TARGET_SCREEN_COORD_FIELD_NUMBER: _builtins.int
    TARGET_MINIMAP_COORD_FIELD_NUMBER: _builtins.int
    QUEUE_COMMAND_FIELD_NUMBER: _builtins.int
    ability_id: _builtins.int
    queue_command: _builtins.bool
    """Equivalent to shift+command."""
    @_builtins.property
    def target_screen_coord(self) -> _common_pb2.PointI: ...
    @_builtins.property
    def target_minimap_coord(self) -> _common_pb2.PointI: ...
    def __init__(
        self,
        *,
        ability_id: _builtins.int | None = ...,
        target_screen_coord: _common_pb2.PointI | None = ...,
        target_minimap_coord: _common_pb2.PointI | None = ...,
        queue_command: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["ability_id", b"ability_id", "queue_command", b"queue_command", "target", b"target", "target_minimap_coord", b"target_minimap_coord", "target_screen_coord", b"target_screen_coord"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ability_id", b"ability_id", "queue_command", b"queue_command", "target", b"target", "target_minimap_coord", b"target_minimap_coord", "target_screen_coord", b"target_screen_coord"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_target: _TypeAlias = _typing.Literal["target_screen_coord", "target_minimap_coord"]  # noqa: Y015
    _WhichOneofArgType_target: _TypeAlias = _typing.Literal["target", b"target"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_target) -> _WhichOneofReturnType_target | None: ...

Global___ActionSpatialUnitCommand: _TypeAlias = ActionSpatialUnitCommand  # noqa: Y015

@_typing.final
class ActionSpatialCameraMove(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CENTER_MINIMAP_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def center_minimap(self) -> _common_pb2.PointI:
        """Simulates a click on the minimap to move the camera."""

    def __init__(
        self,
        *,
        center_minimap: _common_pb2.PointI | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["center_minimap", b"center_minimap"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["center_minimap", b"center_minimap"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ActionSpatialCameraMove: _TypeAlias = ActionSpatialCameraMove  # noqa: Y015

@_typing.final
class ActionSpatialUnitSelectionPoint(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Type:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _TypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[ActionSpatialUnitSelectionPoint._Type.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        Select: ActionSpatialUnitSelectionPoint._Type.ValueType  # 1
        """Equivalent to normal click. Changes selection to unit."""
        Toggle: ActionSpatialUnitSelectionPoint._Type.ValueType  # 2
        """Equivalent to shift+click. Toggle selection of unit."""
        AllType: ActionSpatialUnitSelectionPoint._Type.ValueType  # 3
        """Equivalent to control+click. Selects all units of a given type."""
        AddAllType: ActionSpatialUnitSelectionPoint._Type.ValueType  # 4
        """Equivalent to shift+control+click. Selects all units of a given type."""

    class Type(_Type, metaclass=_TypeEnumTypeWrapper): ...
    Select: ActionSpatialUnitSelectionPoint.Type.ValueType  # 1
    """Equivalent to normal click. Changes selection to unit."""
    Toggle: ActionSpatialUnitSelectionPoint.Type.ValueType  # 2
    """Equivalent to shift+click. Toggle selection of unit."""
    AllType: ActionSpatialUnitSelectionPoint.Type.ValueType  # 3
    """Equivalent to control+click. Selects all units of a given type."""
    AddAllType: ActionSpatialUnitSelectionPoint.Type.ValueType  # 4
    """Equivalent to shift+control+click. Selects all units of a given type."""

    SELECTION_SCREEN_COORD_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    type: Global___ActionSpatialUnitSelectionPoint.Type.ValueType
    @_builtins.property
    def selection_screen_coord(self) -> _common_pb2.PointI: ...
    def __init__(
        self,
        *,
        selection_screen_coord: _common_pb2.PointI | None = ...,
        type: Global___ActionSpatialUnitSelectionPoint.Type.ValueType | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["selection_screen_coord", b"selection_screen_coord", "type", b"type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["selection_screen_coord", b"selection_screen_coord", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ActionSpatialUnitSelectionPoint: _TypeAlias = ActionSpatialUnitSelectionPoint  # noqa: Y015

@_typing.final
class ActionSpatialUnitSelectionRect(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SELECTION_SCREEN_COORD_FIELD_NUMBER: _builtins.int
    SELECTION_ADD_FIELD_NUMBER: _builtins.int
    selection_add: _builtins.bool
    """Equivalent to shift+drag. Adds units to selection."""
    @_builtins.property
    def selection_screen_coord(self) -> _containers.RepeatedCompositeFieldContainer[_common_pb2.RectangleI]:
        """Eventually this should not be an array, but a single field (multiple would be cheating)."""

    def __init__(
        self,
        *,
        selection_screen_coord: _abc.Iterable[_common_pb2.RectangleI] | None = ...,
        selection_add: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["selection_add", b"selection_add"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["selection_add", b"selection_add", "selection_screen_coord", b"selection_screen_coord"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ActionSpatialUnitSelectionRect: _TypeAlias = ActionSpatialUnitSelectionRect  # noqa: Y015
