"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ObservationUI(_message.Message):
    """
    Observation
    """

    DESCRIPTOR: _descriptor.Descriptor

    GROUPS_FIELD_NUMBER: _builtins.int
    SINGLE_FIELD_NUMBER: _builtins.int
    MULTI_FIELD_NUMBER: _builtins.int
    CARGO_FIELD_NUMBER: _builtins.int
    PRODUCTION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def groups(self) -> _containers.RepeatedCompositeFieldContainer[Global___ControlGroup]: ...
    @_builtins.property
    def single(self) -> Global___SinglePanel: ...
    @_builtins.property
    def multi(self) -> Global___MultiPanel: ...
    @_builtins.property
    def cargo(self) -> Global___CargoPanel: ...
    @_builtins.property
    def production(self) -> Global___ProductionPanel: ...
    def __init__(
        self,
        *,
        groups: _abc.Iterable[Global___ControlGroup] | None = ...,
        single: Global___SinglePanel | None = ...,
        multi: Global___MultiPanel | None = ...,
        cargo: Global___CargoPanel | None = ...,
        production: Global___ProductionPanel | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["cargo", b"cargo", "multi", b"multi", "panel", b"panel", "production", b"production", "single", b"single"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cargo", b"cargo", "groups", b"groups", "multi", b"multi", "panel", b"panel", "production", b"production", "single", b"single"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_panel: _TypeAlias = _typing.Literal["single", "multi", "cargo", "production"]  # noqa: Y015
    _WhichOneofArgType_panel: _TypeAlias = _typing.Literal["panel", b"panel"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_panel) -> _WhichOneofReturnType_panel | None: ...

Global___ObservationUI: _TypeAlias = ObservationUI  # noqa: Y015

@_typing.final
class ControlGroup(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONTROL_GROUP_INDEX_FIELD_NUMBER: _builtins.int
    LEADER_UNIT_TYPE_FIELD_NUMBER: _builtins.int
    COUNT_FIELD_NUMBER: _builtins.int
    control_group_index: _builtins.int
    leader_unit_type: _builtins.int
    count: _builtins.int
    def __init__(
        self,
        *,
        control_group_index: _builtins.int | None = ...,
        leader_unit_type: _builtins.int | None = ...,
        count: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["control_group_index", b"control_group_index", "count", b"count", "leader_unit_type", b"leader_unit_type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["control_group_index", b"control_group_index", "count", b"count", "leader_unit_type", b"leader_unit_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ControlGroup: _TypeAlias = ControlGroup  # noqa: Y015

@_typing.final
class UnitInfo(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    UNIT_TYPE_FIELD_NUMBER: _builtins.int
    PLAYER_RELATIVE_FIELD_NUMBER: _builtins.int
    HEALTH_FIELD_NUMBER: _builtins.int
    SHIELDS_FIELD_NUMBER: _builtins.int
    ENERGY_FIELD_NUMBER: _builtins.int
    TRANSPORT_SLOTS_TAKEN_FIELD_NUMBER: _builtins.int
    BUILD_PROGRESS_FIELD_NUMBER: _builtins.int
    ADD_ON_FIELD_NUMBER: _builtins.int
    MAX_HEALTH_FIELD_NUMBER: _builtins.int
    MAX_SHIELDS_FIELD_NUMBER: _builtins.int
    MAX_ENERGY_FIELD_NUMBER: _builtins.int
    unit_type: _builtins.int
    player_relative: _builtins.int
    health: _builtins.int
    shields: _builtins.int
    energy: _builtins.int
    transport_slots_taken: _builtins.int
    build_progress: _builtins.float
    """Range: [0.0, 1.0]"""
    max_health: _builtins.int
    max_shields: _builtins.int
    max_energy: _builtins.int
    @_builtins.property
    def add_on(self) -> Global___UnitInfo: ...
    def __init__(
        self,
        *,
        unit_type: _builtins.int | None = ...,
        player_relative: _builtins.int | None = ...,
        health: _builtins.int | None = ...,
        shields: _builtins.int | None = ...,
        energy: _builtins.int | None = ...,
        transport_slots_taken: _builtins.int | None = ...,
        build_progress: _builtins.float | None = ...,
        add_on: Global___UnitInfo | None = ...,
        max_health: _builtins.int | None = ...,
        max_shields: _builtins.int | None = ...,
        max_energy: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["add_on", b"add_on", "build_progress", b"build_progress", "energy", b"energy", "health", b"health", "max_energy", b"max_energy", "max_health", b"max_health", "max_shields", b"max_shields", "player_relative", b"player_relative", "shields", b"shields", "transport_slots_taken", b"transport_slots_taken", "unit_type", b"unit_type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["add_on", b"add_on", "build_progress", b"build_progress", "energy", b"energy", "health", b"health", "max_energy", b"max_energy", "max_health", b"max_health", "max_shields", b"max_shields", "player_relative", b"player_relative", "shields", b"shields", "transport_slots_taken", b"transport_slots_taken", "unit_type", b"unit_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UnitInfo: _TypeAlias = UnitInfo  # noqa: Y015

@_typing.final
class SinglePanel(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    UNIT_FIELD_NUMBER: _builtins.int
    ATTACK_UPGRADE_LEVEL_FIELD_NUMBER: _builtins.int
    ARMOR_UPGRADE_LEVEL_FIELD_NUMBER: _builtins.int
    SHIELD_UPGRADE_LEVEL_FIELD_NUMBER: _builtins.int
    BUFFS_FIELD_NUMBER: _builtins.int
    attack_upgrade_level: _builtins.int
    armor_upgrade_level: _builtins.int
    shield_upgrade_level: _builtins.int
    @_builtins.property
    def unit(self) -> Global___UnitInfo: ...
    @_builtins.property
    def buffs(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        unit: Global___UnitInfo | None = ...,
        attack_upgrade_level: _builtins.int | None = ...,
        armor_upgrade_level: _builtins.int | None = ...,
        shield_upgrade_level: _builtins.int | None = ...,
        buffs: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["armor_upgrade_level", b"armor_upgrade_level", "attack_upgrade_level", b"attack_upgrade_level", "shield_upgrade_level", b"shield_upgrade_level", "unit", b"unit"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["armor_upgrade_level", b"armor_upgrade_level", "attack_upgrade_level", b"attack_upgrade_level", "buffs", b"buffs", "shield_upgrade_level", b"shield_upgrade_level", "unit", b"unit"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SinglePanel: _TypeAlias = SinglePanel  # noqa: Y015

@_typing.final
class MultiPanel(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    UNITS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def units(self) -> _containers.RepeatedCompositeFieldContainer[Global___UnitInfo]: ...
    def __init__(
        self,
        *,
        units: _abc.Iterable[Global___UnitInfo] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["units", b"units"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MultiPanel: _TypeAlias = MultiPanel  # noqa: Y015

@_typing.final
class CargoPanel(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    UNIT_FIELD_NUMBER: _builtins.int
    PASSENGERS_FIELD_NUMBER: _builtins.int
    SLOTS_AVAILABLE_FIELD_NUMBER: _builtins.int
    slots_available: _builtins.int
    """TODO: Change to cargo size"""
    @_builtins.property
    def unit(self) -> Global___UnitInfo: ...
    @_builtins.property
    def passengers(self) -> _containers.RepeatedCompositeFieldContainer[Global___UnitInfo]: ...
    def __init__(
        self,
        *,
        unit: Global___UnitInfo | None = ...,
        passengers: _abc.Iterable[Global___UnitInfo] | None = ...,
        slots_available: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["slots_available", b"slots_available", "unit", b"unit"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["passengers", b"passengers", "slots_available", b"slots_available", "unit", b"unit"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CargoPanel: _TypeAlias = CargoPanel  # noqa: Y015

@_typing.final
class BuildItem(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ABILITY_ID_FIELD_NUMBER: _builtins.int
    BUILD_PROGRESS_FIELD_NUMBER: _builtins.int
    ability_id: _builtins.int
    build_progress: _builtins.float
    """Range: [0.0, 1.0]"""
    def __init__(
        self,
        *,
        ability_id: _builtins.int | None = ...,
        build_progress: _builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["ability_id", b"ability_id", "build_progress", b"build_progress"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ability_id", b"ability_id", "build_progress", b"build_progress"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___BuildItem: _TypeAlias = BuildItem  # noqa: Y015

@_typing.final
class ProductionPanel(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    UNIT_FIELD_NUMBER: _builtins.int
    BUILD_QUEUE_FIELD_NUMBER: _builtins.int
    PRODUCTION_QUEUE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def unit(self) -> Global___UnitInfo: ...
    @_builtins.property
    def build_queue(self) -> _containers.RepeatedCompositeFieldContainer[Global___UnitInfo]:
        """build_queue ONLY gives information about units that are being produced.
        Use production_queue instead to see both units being trained as well as research in the queue.
        """

    @_builtins.property
    def production_queue(self) -> _containers.RepeatedCompositeFieldContainer[Global___BuildItem]: ...
    def __init__(
        self,
        *,
        unit: Global___UnitInfo | None = ...,
        build_queue: _abc.Iterable[Global___UnitInfo] | None = ...,
        production_queue: _abc.Iterable[Global___BuildItem] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["unit", b"unit"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["build_queue", b"build_queue", "production_queue", b"production_queue", "unit", b"unit"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ProductionPanel: _TypeAlias = ProductionPanel  # noqa: Y015

@_typing.final
class ActionUI(_message.Message):
    """
    Action
    """

    DESCRIPTOR: _descriptor.Descriptor

    CONTROL_GROUP_FIELD_NUMBER: _builtins.int
    SELECT_ARMY_FIELD_NUMBER: _builtins.int
    SELECT_WARP_GATES_FIELD_NUMBER: _builtins.int
    SELECT_LARVA_FIELD_NUMBER: _builtins.int
    SELECT_IDLE_WORKER_FIELD_NUMBER: _builtins.int
    MULTI_PANEL_FIELD_NUMBER: _builtins.int
    CARGO_PANEL_FIELD_NUMBER: _builtins.int
    PRODUCTION_PANEL_FIELD_NUMBER: _builtins.int
    TOGGLE_AUTOCAST_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def control_group(self) -> Global___ActionControlGroup: ...
    @_builtins.property
    def select_army(self) -> Global___ActionSelectArmy: ...
    @_builtins.property
    def select_warp_gates(self) -> Global___ActionSelectWarpGates: ...
    @_builtins.property
    def select_larva(self) -> Global___ActionSelectLarva: ...
    @_builtins.property
    def select_idle_worker(self) -> Global___ActionSelectIdleWorker: ...
    @_builtins.property
    def multi_panel(self) -> Global___ActionMultiPanel: ...
    @_builtins.property
    def cargo_panel(self) -> Global___ActionCargoPanelUnload: ...
    @_builtins.property
    def production_panel(self) -> Global___ActionProductionPanelRemoveFromQueue: ...
    @_builtins.property
    def toggle_autocast(self) -> Global___ActionToggleAutocast: ...
    def __init__(
        self,
        *,
        control_group: Global___ActionControlGroup | None = ...,
        select_army: Global___ActionSelectArmy | None = ...,
        select_warp_gates: Global___ActionSelectWarpGates | None = ...,
        select_larva: Global___ActionSelectLarva | None = ...,
        select_idle_worker: Global___ActionSelectIdleWorker | None = ...,
        multi_panel: Global___ActionMultiPanel | None = ...,
        cargo_panel: Global___ActionCargoPanelUnload | None = ...,
        production_panel: Global___ActionProductionPanelRemoveFromQueue | None = ...,
        toggle_autocast: Global___ActionToggleAutocast | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["action", b"action", "cargo_panel", b"cargo_panel", "control_group", b"control_group", "multi_panel", b"multi_panel", "production_panel", b"production_panel", "select_army", b"select_army", "select_idle_worker", b"select_idle_worker", "select_larva", b"select_larva", "select_warp_gates", b"select_warp_gates", "toggle_autocast", b"toggle_autocast"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["action", b"action", "cargo_panel", b"cargo_panel", "control_group", b"control_group", "multi_panel", b"multi_panel", "production_panel", b"production_panel", "select_army", b"select_army", "select_idle_worker", b"select_idle_worker", "select_larva", b"select_larva", "select_warp_gates", b"select_warp_gates", "toggle_autocast", b"toggle_autocast"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_action: _TypeAlias = _typing.Literal["control_group", "select_army", "select_warp_gates", "select_larva", "select_idle_worker", "multi_panel", "cargo_panel", "production_panel", "toggle_autocast"]  # noqa: Y015
    _WhichOneofArgType_action: _TypeAlias = _typing.Literal["action", b"action"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_action) -> _WhichOneofReturnType_action | None: ...

Global___ActionUI: _TypeAlias = ActionUI  # noqa: Y015

@_typing.final
class ActionControlGroup(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _ControlGroupAction:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _ControlGroupActionEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[ActionControlGroup._ControlGroupAction.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        Recall: ActionControlGroup._ControlGroupAction.ValueType  # 1
        """Equivalent to number hotkey. Replaces current selection with control group."""
        Set: ActionControlGroup._ControlGroupAction.ValueType  # 2
        """Equivalent to Control + number hotkey. Sets control group to current selection."""
        Append: ActionControlGroup._ControlGroupAction.ValueType  # 3
        """Equivalent to Shift + number hotkey. Adds current selection into control group."""
        SetAndSteal: ActionControlGroup._ControlGroupAction.ValueType  # 4
        """Equivalent to Control + Alt + number hotkey. Sets control group to current selection. Units are removed from other control groups."""
        AppendAndSteal: ActionControlGroup._ControlGroupAction.ValueType  # 5
        """Equivalent to Shift + Alt + number hotkey. Adds current selection into control group. Units are removed from other control groups."""

    class ControlGroupAction(_ControlGroupAction, metaclass=_ControlGroupActionEnumTypeWrapper): ...
    Recall: ActionControlGroup.ControlGroupAction.ValueType  # 1
    """Equivalent to number hotkey. Replaces current selection with control group."""
    Set: ActionControlGroup.ControlGroupAction.ValueType  # 2
    """Equivalent to Control + number hotkey. Sets control group to current selection."""
    Append: ActionControlGroup.ControlGroupAction.ValueType  # 3
    """Equivalent to Shift + number hotkey. Adds current selection into control group."""
    SetAndSteal: ActionControlGroup.ControlGroupAction.ValueType  # 4
    """Equivalent to Control + Alt + number hotkey. Sets control group to current selection. Units are removed from other control groups."""
    AppendAndSteal: ActionControlGroup.ControlGroupAction.ValueType  # 5
    """Equivalent to Shift + Alt + number hotkey. Adds current selection into control group. Units are removed from other control groups."""

    ACTION_FIELD_NUMBER: _builtins.int
    CONTROL_GROUP_INDEX_FIELD_NUMBER: _builtins.int
    action: Global___ActionControlGroup.ControlGroupAction.ValueType
    control_group_index: _builtins.int
    def __init__(
        self,
        *,
        action: Global___ActionControlGroup.ControlGroupAction.ValueType | None = ...,
        control_group_index: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["action", b"action", "control_group_index", b"control_group_index"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["action", b"action", "control_group_index", b"control_group_index"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ActionControlGroup: _TypeAlias = ActionControlGroup  # noqa: Y015

@_typing.final
class ActionSelectArmy(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SELECTION_ADD_FIELD_NUMBER: _builtins.int
    selection_add: _builtins.bool
    def __init__(
        self,
        *,
        selection_add: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["selection_add", b"selection_add"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["selection_add", b"selection_add"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ActionSelectArmy: _TypeAlias = ActionSelectArmy  # noqa: Y015

@_typing.final
class ActionSelectWarpGates(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SELECTION_ADD_FIELD_NUMBER: _builtins.int
    selection_add: _builtins.bool
    def __init__(
        self,
        *,
        selection_add: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["selection_add", b"selection_add"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["selection_add", b"selection_add"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ActionSelectWarpGates: _TypeAlias = ActionSelectWarpGates  # noqa: Y015

@_typing.final
class ActionSelectLarva(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___ActionSelectLarva: _TypeAlias = ActionSelectLarva  # noqa: Y015

@_typing.final
class ActionSelectIdleWorker(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Type:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _TypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[ActionSelectIdleWorker._Type.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        Set: ActionSelectIdleWorker._Type.ValueType  # 1
        """Equivalent to click with no modifiers. Replaces selection with single idle worker."""
        Add: ActionSelectIdleWorker._Type.ValueType  # 2
        """Equivalent to shift+click. Adds single idle worker to current selection."""
        All: ActionSelectIdleWorker._Type.ValueType  # 3
        """Equivalent to control+click. Selects all idle workers."""
        AddAll: ActionSelectIdleWorker._Type.ValueType  # 4
        """Equivalent to shift+control+click. Adds all idle workers to current selection."""

    class Type(_Type, metaclass=_TypeEnumTypeWrapper): ...
    Set: ActionSelectIdleWorker.Type.ValueType  # 1
    """Equivalent to click with no modifiers. Replaces selection with single idle worker."""
    Add: ActionSelectIdleWorker.Type.ValueType  # 2
    """Equivalent to shift+click. Adds single idle worker to current selection."""
    All: ActionSelectIdleWorker.Type.ValueType  # 3
    """Equivalent to control+click. Selects all idle workers."""
    AddAll: ActionSelectIdleWorker.Type.ValueType  # 4
    """Equivalent to shift+control+click. Adds all idle workers to current selection."""

    TYPE_FIELD_NUMBER: _builtins.int
    type: Global___ActionSelectIdleWorker.Type.ValueType
    def __init__(
        self,
        *,
        type: Global___ActionSelectIdleWorker.Type.ValueType | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["type", b"type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ActionSelectIdleWorker: _TypeAlias = ActionSelectIdleWorker  # noqa: Y015

@_typing.final
class ActionMultiPanel(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Type:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _TypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[ActionMultiPanel._Type.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        SingleSelect: ActionMultiPanel._Type.ValueType  # 1
        """Click on icon"""
        DeselectUnit: ActionMultiPanel._Type.ValueType  # 2
        """Shift Click on icon"""
        SelectAllOfType: ActionMultiPanel._Type.ValueType  # 3
        """Control Click on icon."""
        DeselectAllOfType: ActionMultiPanel._Type.ValueType  # 4
        """Control+Shift Click on icon."""

    class Type(_Type, metaclass=_TypeEnumTypeWrapper): ...
    SingleSelect: ActionMultiPanel.Type.ValueType  # 1
    """Click on icon"""
    DeselectUnit: ActionMultiPanel.Type.ValueType  # 2
    """Shift Click on icon"""
    SelectAllOfType: ActionMultiPanel.Type.ValueType  # 3
    """Control Click on icon."""
    DeselectAllOfType: ActionMultiPanel.Type.ValueType  # 4
    """Control+Shift Click on icon."""

    TYPE_FIELD_NUMBER: _builtins.int
    UNIT_INDEX_FIELD_NUMBER: _builtins.int
    type: Global___ActionMultiPanel.Type.ValueType
    unit_index: _builtins.int
    def __init__(
        self,
        *,
        type: Global___ActionMultiPanel.Type.ValueType | None = ...,
        unit_index: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["type", b"type", "unit_index", b"unit_index"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["type", b"type", "unit_index", b"unit_index"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ActionMultiPanel: _TypeAlias = ActionMultiPanel  # noqa: Y015

@_typing.final
class ActionCargoPanelUnload(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    UNIT_INDEX_FIELD_NUMBER: _builtins.int
    unit_index: _builtins.int
    def __init__(
        self,
        *,
        unit_index: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["unit_index", b"unit_index"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["unit_index", b"unit_index"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ActionCargoPanelUnload: _TypeAlias = ActionCargoPanelUnload  # noqa: Y015

@_typing.final
class ActionProductionPanelRemoveFromQueue(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    UNIT_INDEX_FIELD_NUMBER: _builtins.int
    unit_index: _builtins.int
    def __init__(
        self,
        *,
        unit_index: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["unit_index", b"unit_index"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["unit_index", b"unit_index"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ActionProductionPanelRemoveFromQueue: _TypeAlias = ActionProductionPanelRemoveFromQueue  # noqa: Y015

@_typing.final
class ActionToggleAutocast(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ABILITY_ID_FIELD_NUMBER: _builtins.int
    ability_id: _builtins.int
    def __init__(
        self,
        *,
        ability_id: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["ability_id", b"ability_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ability_id", b"ability_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ActionToggleAutocast: _TypeAlias = ActionToggleAutocast  # noqa: Y015
